// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.
//
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// ------------------------------------------------
//
// This file is automatically generated.
// Please do not edit these files manually.
//
// ------------------------------------------------

#nullable restore

using System;
using System.Linq;
using Elastic.Clients.Elasticsearch.Serialization;

namespace Elastic.Clients.Elasticsearch.Analysis;

public static class NoriDecompoundModeCodeFormatter
{
	public static void FormatCode(Elastic.Clients.Elasticsearch.Analysis.NoriDecompoundMode instance, RequestConverter.CodeWriter writer)
	{
		switch (instance)
		{
			case Elastic.Clients.Elasticsearch.Analysis.NoriDecompoundMode.Discard:
				writer.WriteTypeRef("Elastic.Clients.Elasticsearch.Analysis.NoriDecompoundMode");
				writer.Write(".Discard");
				break;
			case Elastic.Clients.Elasticsearch.Analysis.NoriDecompoundMode.Mixed:
				writer.WriteTypeRef("Elastic.Clients.Elasticsearch.Analysis.NoriDecompoundMode");
				writer.Write(".Mixed");
				break;
			case Elastic.Clients.Elasticsearch.Analysis.NoriDecompoundMode.None:
				writer.WriteTypeRef("Elastic.Clients.Elasticsearch.Analysis.NoriDecompoundMode");
				writer.Write(".None");
				break;
			default:
				throw new System.ArgumentOutOfRangeException(nameof(instance), instance, "Unexpected NoriDecompoundMode value.");
		}
	}
}