// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.
//
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// ------------------------------------------------
//
// This file is automatically generated.
// Please do not edit these files manually.
//
// ------------------------------------------------

#nullable restore

using System;
using System.Linq;
using Elastic.Clients.Elasticsearch.Serialization;

namespace Elastic.Clients.Elasticsearch.Aggregations;

public partial class GeoDistanceAggregation : RequestConverter.ICodeFormattable
{
	public void FormatCode(RequestConverter.CodeWriter writer)
	{
		var initializer = writer.BeginObjectInitializer("GeoDistanceAggregation", false);
		if (DistanceType is not null)
		{
			initializer.Property("DistanceType");
			Elastic.Clients.Elasticsearch.GeoDistanceTypeCodeFormatter.FormatCode(DistanceType.Value, writer);
		}

		if (Field is not null)
		{
			initializer.Property("Field");
			Field.FormatCode(writer);
		}

		if (Origin is not null)
		{
			initializer.Property("Origin");
			Origin.FormatCode(writer);
		}

		if (Ranges is not null)
		{
			initializer.Property("Ranges");
			writer.WriteInlineList(Ranges, (w, item) => { item.FormatCode(w); });
		}

		if (Unit is not null)
		{
			initializer.Property("Unit");
			Elastic.Clients.Elasticsearch.DistanceUnitCodeFormatter.FormatCode(Unit.Value, writer);
		}

		initializer.Dispose();
	}
}