// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.
//
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// ------------------------------------------------
//
// This file is automatically generated.
// Please do not edit these files manually.
//
// ------------------------------------------------

#nullable restore

using Elastic.Clients.Elasticsearch.Serialization;
using System;
using System.Linq;

namespace Elastic.Clients.Elasticsearch.Core.HealthReport;

/// <include file="../../../SpecReferences.xml" path="doc/member[@key='_global.health_report.Diagnosis']/*"/>
[System.Text.Json.Serialization.JsonConverter(typeof(Elastic.Clients.Elasticsearch.Core.HealthReport.Json.DiagnosisConverter))]
public sealed partial class Diagnosis
{
	[System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
	public Diagnosis(string action, Elastic.Clients.Elasticsearch.Core.HealthReport.DiagnosisAffectedResources affectedResources, string cause, string helpUrl, string id)
	{
		Action = action;
		AffectedResources = affectedResources;
		Cause = cause;
		HelpUrl = helpUrl;
		Id = id;
	}

	public Diagnosis()
	{
	}

	[System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
	internal Diagnosis(Elastic.Clients.Elasticsearch.Serialization.JsonConstructorSentinel sentinel)
	{
		_ = sentinel;
	}

	public required string Action { get; set; }
	public required Elastic.Clients.Elasticsearch.Core.HealthReport.DiagnosisAffectedResources AffectedResources { get; set; }
	public required string Cause { get; set; }
	public required string HelpUrl { get; set; }
	public required string Id { get; set; }
}