:github: https://github.com/elastic/elasticsearch-net

:stackoverflow: http://stackoverflow.com

[[introduction]]
== Introduction

You've reached the documentation page for `Elasticsearch.Net` and `NEST`, The two official .NET clients for Elasticsearch. 

=== Why two clients?

`Elasticsearch.Net` is a very low level, dependency free, client that has no opinions about how you build and represent your requests and responses. It has abstracted 
enough so that **all** the Elasticsearch API endpoints are represented as methods but not too much to get in the way of how you want to build 
your json/request/response objects. It also comes with built in, configurable/overridable, cluster failover retry mechanisms. Elasticsearch is _elastic_ so why not your client?

`NEST` is a high level client that has the advantage of having mapped all the request and response objects, 
comes with a strongly typed query DSL that maps 1 to 1 with the Elasticsearch query DSL, and takes advantage of specific .NET features such as 
<<covariant-search-results, covariant results>> and <<auto-map, auto mapping of POCOs>>. NEST internally uses and still exposes the low level `Elasticsearch.Net` client.

Please read the getting started guide for both <<elasticsearch-net,Elasticsearch.Net>> and <<nest,NEST>>.

=== Questions, bugs, comments, requests

All of these are more then welcome on the {github}/issues[github issues pages]! We try to at least reply within the same day.

We also monitor question tagged with {stackoverflow}/questions/tagged/nest['nest' on stackoverflow] or 
{stackoverflow}/questions/tagged/elasticsearch-net['elasticsearch-net' on stackoverflow], as well as https://discuss.elastic.co[discussions on our discourse site]

