// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.
//
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// ------------------------------------------------
//
// This file is automatically generated.
// Please do not edit these files manually.
//
// ------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Text.Json;
using System.Text.Json.Serialization;

#nullable restore
namespace Elastic.Clients.Elasticsearch
{
	public abstract partial class BulkResponseItemBase
	{
		[JsonInclude]
		[JsonPropertyName("_id")]
		public string? Id { get; init; }

		[JsonInclude]
		[JsonPropertyName("_index")]
		public string Index { get; init; }

		[JsonInclude]
		[JsonPropertyName("_primary_term")]
		public long? PrimaryTerm { get; init; }

		[JsonInclude]
		[JsonPropertyName("_seq_no")]
		public long? SeqNo { get; init; }

		[JsonInclude]
		[JsonPropertyName("_shards")]
		public Elastic.Clients.Elasticsearch.ShardStatistics? Shards { get; init; }

		[JsonInclude]
		[JsonPropertyName("_version")]
		public long? Version { get; init; }

		[JsonInclude]
		[JsonPropertyName("error")]
		public Elastic.Clients.Elasticsearch.ErrorCause? Error { get; init; }

		[JsonInclude]
		[JsonPropertyName("forced_refresh")]
		public bool? ForcedRefresh { get; init; }

		[JsonInclude]
		[JsonPropertyName("get")]
		public Elastic.Clients.Elasticsearch.InlineGet<LazyDocument>? Get { get; init; }

		[JsonInclude]
		[JsonPropertyName("result")]
		public string? Result { get; init; }

		[JsonInclude]
		[JsonPropertyName("status")]
		public int Status { get; init; }
	}
}