// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.
//
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// ------------------------------------------------
//
// This file is automatically generated.
// Please do not edit these files manually.
//
// ------------------------------------------------

#nullable restore

using System;
using System.Linq;
using Elastic.Clients.Elasticsearch.Serialization;

namespace Elastic.Clients.Elasticsearch.IndexManagement;

[System.Text.Json.Serialization.JsonConverter(typeof(Elastic.Clients.Elasticsearch.IndexManagement.Json.SettingsSimilarityIbConverter))]
public sealed partial class SettingsSimilarityIb : Elastic.Clients.Elasticsearch.IndexManagement.ISettingsSimilarity
{
	[System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
	public SettingsSimilarityIb(Elastic.Clients.Elasticsearch.IBDistribution distribution, Elastic.Clients.Elasticsearch.IBLambda lambda, Elastic.Clients.Elasticsearch.Normalization normalization)
	{
		Distribution = distribution;
		Lambda = lambda;
		Normalization = normalization;
	}
#if NET7_0_OR_GREATER
	public SettingsSimilarityIb()
	{
	}
#endif
#if !NET7_0_OR_GREATER
	[System.Obsolete("The type contains required properties that must be initialized. Please use an alternative constructor to ensure all required values are properly set.")]
	public SettingsSimilarityIb()
	{
	}
#endif
	[System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
	internal SettingsSimilarityIb(Elastic.Clients.Elasticsearch.Serialization.JsonConstructorSentinel sentinel)
	{
		_ = sentinel;
	}

	public
#if NET7_0_OR_GREATER
	required
#endif
	Elastic.Clients.Elasticsearch.IBDistribution Distribution { get; set; }
	public
#if NET7_0_OR_GREATER
	required
#endif
	Elastic.Clients.Elasticsearch.IBLambda Lambda { get; set; }
	public
#if NET7_0_OR_GREATER
	required
#endif
	Elastic.Clients.Elasticsearch.Normalization Normalization { get; set; }

	public string Type => "IB";
}

public readonly partial struct SettingsSimilarityIbDescriptor
{
	internal Elastic.Clients.Elasticsearch.IndexManagement.SettingsSimilarityIb Instance { get; init; }

	[System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
	public SettingsSimilarityIbDescriptor(Elastic.Clients.Elasticsearch.IndexManagement.SettingsSimilarityIb instance)
	{
		Instance = instance;
	}

	[System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
	public SettingsSimilarityIbDescriptor()
	{
		Instance = new Elastic.Clients.Elasticsearch.IndexManagement.SettingsSimilarityIb(Elastic.Clients.Elasticsearch.Serialization.JsonConstructorSentinel.Instance);
	}

	public static explicit operator Elastic.Clients.Elasticsearch.IndexManagement.SettingsSimilarityIbDescriptor(Elastic.Clients.Elasticsearch.IndexManagement.SettingsSimilarityIb instance) => new Elastic.Clients.Elasticsearch.IndexManagement.SettingsSimilarityIbDescriptor(instance);
	public static implicit operator Elastic.Clients.Elasticsearch.IndexManagement.SettingsSimilarityIb(Elastic.Clients.Elasticsearch.IndexManagement.SettingsSimilarityIbDescriptor descriptor) => descriptor.Instance;

	public Elastic.Clients.Elasticsearch.IndexManagement.SettingsSimilarityIbDescriptor Distribution(Elastic.Clients.Elasticsearch.IBDistribution value)
	{
		Instance.Distribution = value;
		return this;
	}

	public Elastic.Clients.Elasticsearch.IndexManagement.SettingsSimilarityIbDescriptor Lambda(Elastic.Clients.Elasticsearch.IBLambda value)
	{
		Instance.Lambda = value;
		return this;
	}

	public Elastic.Clients.Elasticsearch.IndexManagement.SettingsSimilarityIbDescriptor Normalization(Elastic.Clients.Elasticsearch.Normalization value)
	{
		Instance.Normalization = value;
		return this;
	}

	[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	internal static Elastic.Clients.Elasticsearch.IndexManagement.SettingsSimilarityIb Build(System.Action<Elastic.Clients.Elasticsearch.IndexManagement.SettingsSimilarityIbDescriptor> action)
	{
		var builder = new Elastic.Clients.Elasticsearch.IndexManagement.SettingsSimilarityIbDescriptor(new Elastic.Clients.Elasticsearch.IndexManagement.SettingsSimilarityIb(Elastic.Clients.Elasticsearch.Serialization.JsonConstructorSentinel.Instance));
		action.Invoke(builder);
		return builder.Instance;
	}
}