:ref_current: https://www.elastic.co/guide/en/elasticsearch/reference/6.1

:github: https://github.com/elastic/elasticsearch-net

:nuget: https://www.nuget.org/packages

////
IMPORTANT NOTE
==============
This file has been generated from https://github.com/elastic/elasticsearch-net/tree/master/src/Tests/Aggregations/Bucket/Terms/TermsAggregationUsageTests.cs. 
If you wish to submit a PR for any spelling mistakes, typos or grammatical errors for this file,
please modify the original csharp file found at the link and submit the PR with that change. Thanks!
////

[[terms-aggregation-usage]]
=== Terms Aggregation Usage

A multi-bucket value source based aggregation where buckets are dynamically built - one per unique value.

See the Elasticsearch documentation on {ref_current}/search-aggregations-bucket-terms-aggregation.html[terms aggregation] for more detail.

==== Handling Responses

[source,csharp]
----
response.ShouldBeValid();
var states = response.Aggregations.Terms("states");
states.Should().NotBeNull();
states.DocCountErrorUpperBound.Should().HaveValue();
states.SumOtherDocCount.Should().HaveValue();
states.Buckets.Should().NotBeNull();
states.Buckets.Count.Should().BeGreaterThan(0);
foreach (var item in states.Buckets)
{
    item.Key.Should().NotBeNullOrEmpty();
    item.DocCount.Should().BeGreaterOrEqualTo(1);
}
states.Meta.Should().NotBeNull().And.HaveCount(1);
states.Meta["foo"].Should().Be("bar");
----

[[terms-pattern-filter]]
[float]
== Filtering with a regular expression pattern

Using terms aggregation with filtering to include values using a regular expression pattern

[source,csharp]
----
response.ShouldBeValid();
var states = response.Aggregations.Terms("states");
states.Should().NotBeNull();
states.DocCountErrorUpperBound.Should().HaveValue();
states.SumOtherDocCount.Should().HaveValue();
states.Buckets.Should().NotBeNull();
states.Buckets.Count.Should().BeGreaterThan(0);
foreach (var item in states.Buckets)
{
    item.Key.Should().NotBeNullOrEmpty();
    item.DocCount.Should().BeGreaterOrEqualTo(1);
}
states.Meta.Should().NotBeNull().And.HaveCount(1);
states.Meta["foo"].Should().Be("bar");
----

[[terms-exact-value-filter]]
[float]
== Filtering with exact values

Using terms aggregation with filtering to include only specific values

[source,csharp]
----
response.ShouldBeValid();
var states = response.Aggregations.Terms("states");
states.Should().NotBeNull();
states.DocCountErrorUpperBound.Should().HaveValue();
states.SumOtherDocCount.Should().HaveValue();
states.Buckets.Should().NotBeNull();
states.Buckets.Count.Should().BeGreaterThan(0);
foreach (var item in states.Buckets)
{
    item.Key.Should().NotBeNullOrEmpty();
    item.DocCount.Should().BeGreaterOrEqualTo(1);
}
states.Meta.Should().NotBeNull().And.HaveCount(1);
states.Meta["foo"].Should().Be("bar");
----

[float]
== Filtering with partitions

A terms aggregation that uses partitioning to filter the terms that are returned in the response. Further terms
can be returned by issuing additional requests with an incrementing `partition` number.

[NOTE]
--
Partitioning is available only in Elasticsearch 5.2.0+

--

[source,csharp]
----
response.ShouldBeValid();
var commits = response.Aggregations.Terms<int>("commits");
commits.Should().NotBeNull();
commits.DocCountErrorUpperBound.Should().HaveValue();
commits.SumOtherDocCount.Should().HaveValue();
commits.Buckets.Should().NotBeNull();
commits.Buckets.Count.Should().BeGreaterThan(0);
foreach (var item in commits.Buckets)
{
    item.Key.Should().BeGreaterThan(0);
    item.DocCount.Should().BeGreaterOrEqualTo(1);
}
----

[float]
== Numeric fields

A terms aggregation on a numeric field

[source,csharp]
----
response.ShouldBeValid();
var commits = response.Aggregations.Terms<int>("commits");
commits.Should().NotBeNull();
commits.DocCountErrorUpperBound.Should().HaveValue();
commits.SumOtherDocCount.Should().HaveValue();
commits.Buckets.Should().NotBeNull();
commits.Buckets.Count.Should().BeGreaterThan(0);
foreach (var item in commits.Buckets)
{
    item.Key.Should().BeGreaterThan(0);
    item.DocCount.Should().BeGreaterOrEqualTo(1);
}
commits.Buckets.Should().Contain(b => b.DocCountErrorUpperBound.HasValue);
----

[float]
== Nested terms aggregations

A terms aggregation returns buckets that can contain more aggregations

[source,csharp]
----
response.ShouldBeValid();
var commits = response.Aggregations.Terms<int>("commits");
commits.Should().NotBeNull();
commits.DocCountErrorUpperBound.Should().HaveValue();
commits.SumOtherDocCount.Should().HaveValue();
commits.Buckets.Should().NotBeNull();
commits.Buckets.Count.Should().BeGreaterThan(0);
foreach (var item in commits.Buckets)
{
    item.Key.Should().BeGreaterThan(0);
    item.DocCount.Should().BeGreaterOrEqualTo(1);
    var states = item.Terms("state");
    states.Should().NotBeNull();
    states.Buckets.Should().NotBeEmpty();
    states.Meta.Should().NotBeEmpty("meta").And.ContainKey("x");
    foreach (var b in states.Buckets)
    {
        b.DocCount.Should().BeGreaterThan(0);
        b.Key.Should().NotBeNullOrEmpty();
    }
}
----

[float]
== Typed Keys aggregations

Starting with Elasticsearch 6.x you can provide a `typed_keys` parameter which will prefix all the aggregation names
with the type of aggregation that is returned. The following modifies the previous nested terms aggregation and sends it again
but this time with the `typed_keys` option set. The client should treat this in a an opaque fashion so let's assert that it does.

==== Fluent DSL example

[source,csharp]
----
f => base.Fluent(f.TypedKeys())
----

==== Object Initializer syntax example

[source,csharp]
----
var r = base.Initializer;
r.TypedKeys = true;
return r;
----

