// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.
//
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// ------------------------------------------------
//
// This file is automatically generated.
// Please do not edit these files manually.
//
// ------------------------------------------------

#nullable restore

using Elastic.Clients.Elasticsearch.Serialization;
using System;
using System.Linq;

namespace Elastic.Clients.Elasticsearch.Core.GetScriptLanguages;

/// <include file="../../../SpecReferences.xml" path="doc/member[@key='_global.get_script_languages.LanguageContext']/*"/>
[System.Text.Json.Serialization.JsonConverter(typeof(Elastic.Clients.Elasticsearch.Core.GetScriptLanguages.Json.LanguageContextConverter))]
public sealed partial class LanguageContext
{
	[System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
	public LanguageContext(System.Collections.Generic.IReadOnlyCollection<string> contexts, Elastic.Clients.Elasticsearch.ScriptLanguage language)
	{
		Contexts = contexts;
		Language = language;
	}

	public LanguageContext()
	{
	}

	[System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
	internal LanguageContext(Elastic.Clients.Elasticsearch.Serialization.JsonConstructorSentinel sentinel)
	{
		_ = sentinel;
	}

	public required System.Collections.Generic.IReadOnlyCollection<string> Contexts { get; set; }
	public required Elastic.Clients.Elasticsearch.ScriptLanguage Language { get; set; }
}