// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.
//
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// ------------------------------------------------
//
// This file is automatically generated.
// Please do not edit these files manually.
//
// ------------------------------------------------

#nullable restore

using Elastic.Clients.Elasticsearch.Serverless.Fluent;
using Elastic.Clients.Elasticsearch.Serverless.Serialization;
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq.Expressions;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Elastic.Clients.Elasticsearch.Serverless.Security;

[JsonConverter(typeof(RoleMappingRuleConverter))]
public sealed partial class RoleMappingRule
{
	internal RoleMappingRule(string variantName, object variant)
	{
		if (variantName is null)
			throw new ArgumentNullException(nameof(variantName));
		if (variant is null)
			throw new ArgumentNullException(nameof(variant));
		if (string.IsNullOrWhiteSpace(variantName))
			throw new ArgumentException("Variant name must not be empty or whitespace.");
		VariantName = variantName;
		Variant = variant;
	}

	internal object Variant { get; }
	internal string VariantName { get; }

	public static RoleMappingRule All(IReadOnlyCollection<Elastic.Clients.Elasticsearch.Serverless.Security.RoleMappingRule> roleMappingRule) => new RoleMappingRule("all", roleMappingRule);
	public static RoleMappingRule Any(IReadOnlyCollection<Elastic.Clients.Elasticsearch.Serverless.Security.RoleMappingRule> roleMappingRule) => new RoleMappingRule("any", roleMappingRule);
	public static RoleMappingRule Except(Elastic.Clients.Elasticsearch.Serverless.Security.RoleMappingRule roleMappingRule) => new RoleMappingRule("except", roleMappingRule);
	public static RoleMappingRule Field(Elastic.Clients.Elasticsearch.Serverless.Security.FieldRule fieldRule) => new RoleMappingRule("field", fieldRule);

	public bool TryGet<T>([NotNullWhen(true)] out T? result) where T : class
	{
		result = default;
		if (Variant is T variant)
		{
			result = variant;
			return true;
		}

		return false;
	}
}

internal sealed partial class RoleMappingRuleConverter : JsonConverter<RoleMappingRule>
{
	public override RoleMappingRule Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
	{
		if (reader.TokenType != JsonTokenType.StartObject)
		{
			throw new JsonException("Expected start token.");
		}

		object? variantValue = default;
		string? variantNameValue = default;
		while (reader.Read() && reader.TokenType != JsonTokenType.EndObject)
		{
			if (reader.TokenType != JsonTokenType.PropertyName)
			{
				throw new JsonException("Expected a property name token.");
			}

			if (reader.TokenType != JsonTokenType.PropertyName)
			{
				throw new JsonException("Expected a property name token representing the name of an Elasticsearch field.");
			}

			var propertyName = reader.GetString();
			reader.Read();
			if (propertyName == "all")
			{
				variantValue = JsonSerializer.Deserialize<ICollection<Elastic.Clients.Elasticsearch.Serverless.Security.RoleMappingRule>?>(ref reader, options);
				variantNameValue = propertyName;
				continue;
			}

			if (propertyName == "any")
			{
				variantValue = JsonSerializer.Deserialize<ICollection<Elastic.Clients.Elasticsearch.Serverless.Security.RoleMappingRule>?>(ref reader, options);
				variantNameValue = propertyName;
				continue;
			}

			if (propertyName == "except")
			{
				variantValue = JsonSerializer.Deserialize<Elastic.Clients.Elasticsearch.Serverless.Security.RoleMappingRule?>(ref reader, options);
				variantNameValue = propertyName;
				continue;
			}

			if (propertyName == "field")
			{
				variantValue = JsonSerializer.Deserialize<Elastic.Clients.Elasticsearch.Serverless.Security.FieldRule?>(ref reader, options);
				variantNameValue = propertyName;
				continue;
			}

			throw new JsonException($"Unknown property name '{propertyName}' received while deserializing the 'RoleMappingRule' from the response.");
		}

		var result = new RoleMappingRule(variantNameValue, variantValue);
		return result;
	}

	public override void Write(Utf8JsonWriter writer, RoleMappingRule value, JsonSerializerOptions options)
	{
		writer.WriteStartObject();
		if (value.VariantName is not null && value.Variant is not null)
		{
			writer.WritePropertyName(value.VariantName);
			switch (value.VariantName)
			{
				case "all":
					JsonSerializer.Serialize<IReadOnlyCollection<Elastic.Clients.Elasticsearch.Serverless.Security.RoleMappingRule>>(writer, (IReadOnlyCollection<Elastic.Clients.Elasticsearch.Serverless.Security.RoleMappingRule>)value.Variant, options);
					break;
				case "any":
					JsonSerializer.Serialize<IReadOnlyCollection<Elastic.Clients.Elasticsearch.Serverless.Security.RoleMappingRule>>(writer, (IReadOnlyCollection<Elastic.Clients.Elasticsearch.Serverless.Security.RoleMappingRule>)value.Variant, options);
					break;
				case "except":
					JsonSerializer.Serialize<Elastic.Clients.Elasticsearch.Serverless.Security.RoleMappingRule>(writer, (Elastic.Clients.Elasticsearch.Serverless.Security.RoleMappingRule)value.Variant, options);
					break;
				case "field":
					JsonSerializer.Serialize<Elastic.Clients.Elasticsearch.Serverless.Security.FieldRule>(writer, (Elastic.Clients.Elasticsearch.Serverless.Security.FieldRule)value.Variant, options);
					break;
			}
		}

		writer.WriteEndObject();
	}
}

public sealed partial class RoleMappingRuleDescriptor<TDocument> : SerializableDescriptor<RoleMappingRuleDescriptor<TDocument>>
{
	internal RoleMappingRuleDescriptor(Action<RoleMappingRuleDescriptor<TDocument>> configure) => configure.Invoke(this);

	public RoleMappingRuleDescriptor() : base()
	{
	}

	private bool ContainsVariant { get; set; }
	private string ContainedVariantName { get; set; }
	private object Variant { get; set; }
	private Descriptor Descriptor { get; set; }

	private RoleMappingRuleDescriptor<TDocument> Set<T>(Action<T> descriptorAction, string variantName) where T : Descriptor
	{
		ContainedVariantName = variantName;
		ContainsVariant = true;
		var descriptor = (T)Activator.CreateInstance(typeof(T), true);
		descriptorAction?.Invoke(descriptor);
		Descriptor = descriptor;
		return Self;
	}

	private RoleMappingRuleDescriptor<TDocument> Set(object variant, string variantName)
	{
		Variant = variant;
		ContainedVariantName = variantName;
		ContainsVariant = true;
		return Self;
	}

	public RoleMappingRuleDescriptor<TDocument> All(IReadOnlyCollection<Elastic.Clients.Elasticsearch.Serverless.Security.RoleMappingRule> roleMappingRule) => Set(roleMappingRule, "all");
	public RoleMappingRuleDescriptor<TDocument> All(Action<Elastic.Clients.Elasticsearch.Serverless.Security.RoleMappingRuleDescriptor> configure) => Set(configure, "all");
	public RoleMappingRuleDescriptor<TDocument> Any(IReadOnlyCollection<Elastic.Clients.Elasticsearch.Serverless.Security.RoleMappingRule> roleMappingRule) => Set(roleMappingRule, "any");
	public RoleMappingRuleDescriptor<TDocument> Any(Action<Elastic.Clients.Elasticsearch.Serverless.Security.RoleMappingRuleDescriptor> configure) => Set(configure, "any");
	public RoleMappingRuleDescriptor<TDocument> Except(Elastic.Clients.Elasticsearch.Serverless.Security.RoleMappingRule roleMappingRule) => Set(roleMappingRule, "except");
	public RoleMappingRuleDescriptor<TDocument> Except(Action<Elastic.Clients.Elasticsearch.Serverless.Security.RoleMappingRuleDescriptor> configure) => Set(configure, "except");
	public RoleMappingRuleDescriptor<TDocument> Field(Elastic.Clients.Elasticsearch.Serverless.Security.FieldRule fieldRule) => Set(fieldRule, "field");
	public RoleMappingRuleDescriptor<TDocument> Field(Action<Elastic.Clients.Elasticsearch.Serverless.Security.FieldRuleDescriptor> configure) => Set(configure, "field");

	protected override void Serialize(Utf8JsonWriter writer, JsonSerializerOptions options, IElasticsearchClientSettings settings)
	{
		writer.WriteStartObject();
		if (!string.IsNullOrEmpty(ContainedVariantName))
		{
			writer.WritePropertyName(ContainedVariantName);
			if (Variant is not null)
			{
				JsonSerializer.Serialize(writer, Variant, Variant.GetType(), options);
				writer.WriteEndObject();
				return;
			}

			JsonSerializer.Serialize(writer, Descriptor, Descriptor.GetType(), options);
		}

		writer.WriteEndObject();
	}
}

public sealed partial class RoleMappingRuleDescriptor : SerializableDescriptor<RoleMappingRuleDescriptor>
{
	internal RoleMappingRuleDescriptor(Action<RoleMappingRuleDescriptor> configure) => configure.Invoke(this);

	public RoleMappingRuleDescriptor() : base()
	{
	}

	private bool ContainsVariant { get; set; }
	private string ContainedVariantName { get; set; }
	private object Variant { get; set; }
	private Descriptor Descriptor { get; set; }

	private RoleMappingRuleDescriptor Set<T>(Action<T> descriptorAction, string variantName) where T : Descriptor
	{
		ContainedVariantName = variantName;
		ContainsVariant = true;
		var descriptor = (T)Activator.CreateInstance(typeof(T), true);
		descriptorAction?.Invoke(descriptor);
		Descriptor = descriptor;
		return Self;
	}

	private RoleMappingRuleDescriptor Set(object variant, string variantName)
	{
		Variant = variant;
		ContainedVariantName = variantName;
		ContainsVariant = true;
		return Self;
	}

	public RoleMappingRuleDescriptor All(IReadOnlyCollection<Elastic.Clients.Elasticsearch.Serverless.Security.RoleMappingRule> roleMappingRule) => Set(roleMappingRule, "all");
	public RoleMappingRuleDescriptor All(Action<Elastic.Clients.Elasticsearch.Serverless.Security.RoleMappingRuleDescriptor> configure) => Set(configure, "all");
	public RoleMappingRuleDescriptor Any(IReadOnlyCollection<Elastic.Clients.Elasticsearch.Serverless.Security.RoleMappingRule> roleMappingRule) => Set(roleMappingRule, "any");
	public RoleMappingRuleDescriptor Any(Action<Elastic.Clients.Elasticsearch.Serverless.Security.RoleMappingRuleDescriptor> configure) => Set(configure, "any");
	public RoleMappingRuleDescriptor Except(Elastic.Clients.Elasticsearch.Serverless.Security.RoleMappingRule roleMappingRule) => Set(roleMappingRule, "except");
	public RoleMappingRuleDescriptor Except(Action<Elastic.Clients.Elasticsearch.Serverless.Security.RoleMappingRuleDescriptor> configure) => Set(configure, "except");
	public RoleMappingRuleDescriptor Field(Elastic.Clients.Elasticsearch.Serverless.Security.FieldRule fieldRule) => Set(fieldRule, "field");
	public RoleMappingRuleDescriptor Field(Action<Elastic.Clients.Elasticsearch.Serverless.Security.FieldRuleDescriptor> configure) => Set(configure, "field");

	protected override void Serialize(Utf8JsonWriter writer, JsonSerializerOptions options, IElasticsearchClientSettings settings)
	{
		writer.WriteStartObject();
		if (!string.IsNullOrEmpty(ContainedVariantName))
		{
			writer.WritePropertyName(ContainedVariantName);
			if (Variant is not null)
			{
				JsonSerializer.Serialize(writer, Variant, Variant.GetType(), options);
				writer.WriteEndObject();
				return;
			}

			JsonSerializer.Serialize(writer, Descriptor, Descriptor.GetType(), options);
		}

		writer.WriteEndObject();
	}
}