cd /d %~dp0
mklink ".\src\Utf8Json.UnityClient\Assets\Scripts\Utf8Json\Attributes.cs" "..\..\..\..\Utf8Json\Attributes.cs"
mklink ".\src\Utf8Json.UnityClient\Assets\Scripts\Utf8Json\IJsonFormatter.cs" "..\..\..\..\Utf8Json\IJsonFormatter.cs"
mklink ".\src\Utf8Json.UnityClient\Assets\Scripts\Utf8Json\IJsonFormatterResolver.cs" "..\..\..\..\Utf8Json\IJsonFormatterResolver.cs"
mklink ".\src\Utf8Json.UnityClient\Assets\Scripts\Utf8Json\JsonReader.cs" "..\..\..\..\Utf8Json\JsonReader.cs"
mklink ".\src\Utf8Json.UnityClient\Assets\Scripts\Utf8Json\JsonWriter.cs" "..\..\..\..\Utf8Json\JsonWriter.cs"
mklink ".\src\Utf8Json.UnityClient\Assets\Scripts\Utf8Json\JsonSerializer.cs" "..\..\..\..\Utf8Json\JsonSerializer.cs"
mklink ".\src\Utf8Json.UnityClient\Assets\Scripts\Utf8Json\JsonSerializer.NonGeneric.cs" "..\..\..\..\Utf8Json\JsonSerializer.NonGeneric.cs"
mklink ".\src\Utf8Json.UnityClient\Assets\Scripts\Utf8Json\JsonToken.cs" "..\..\..\..\Utf8Json\JsonToken.cs"
mklink /D ".\src\Utf8Json.UnityClient\Assets\Scripts\Utf8Json\Resolvers" "..\..\..\..\Utf8Json\Resolvers"
mklink /D ".\src\Utf8Json.UnityClient\Assets\Scripts\Utf8Json\Formatters" "..\..\..\..\Utf8Json\Formatters"
mklink /D ".\src\Utf8Json.UnityClient\Assets\Scripts\Utf8Json\Internal" "..\..\..\..\Utf8Json\Internal"
mklink ".\src\Utf8Json.UnityClient\Assets\Scripts\Utf8Json\Unity\ResolverAndFormatters.cs" "..\..\..\..\..\Utf8Json.UnityShims\ResolverAndFormatters.cs"