:ref_current: https://www.elastic.co/guide/en/elasticsearch/reference/6.2

:github: https://github.com/elastic/elasticsearch-net

:nuget: https://www.nuget.org/packages

////
IMPORTANT NOTE
==============
This file has been generated from https://github.com/elastic/elasticsearch-net/tree/master/src/Tests/ClientConcepts/Troubleshooting/DebugInformation.doc.cs. 
If you wish to submit a PR for any spelling mistakes, typos or grammatical errors for this file,
please modify the original csharp file found at the link and submit the PR with that change. Thanks!
////

[[debug-information]]
=== Debug information

Every response from Elasticsearch.Net and NEST contains a `DebugInformation` property
that provides a human readable description of what happened during the request for both successful and
failed requests

[source,csharp]
----
var response = client.Search<Project>(s => s
    .Query(q => q
        .MatchAll()
    )
);

response.DebugInformation.Should().Contain("Valid NEST response");
----

This can be useful in tracking down numerous problems and can also be useful when filing an
{github}/issues[issue] on our github repository.

By default, the request and response bytes are not available within the debug information, but
can be enabled globally on Connection Settings

[source,csharp]
----
var connectionPool = new SingleNodeConnectionPool(new Uri("http://localhost:9200"));

var settings = new ConnectionSettings(connectionPool)
    .DisableDirectStreaming(); <1>

var client = new ElasticClient(settings);
----
<1> disable direct streaming for *all* requests

or on a _per request_ basis

[source,csharp]
----
var response = client.Search<Project>(s => s
    .RequestConfiguration(r => r
        .DisableDirectStreaming() <1>
    )
    .Query(q => q
        .MatchAll()
    )
);

response.DebugInformation.Should().Contain("\"match_all\":");
----
<1> disable direct streaming for *this* request

