// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.
//
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// ------------------------------------------------
//
// This file is automatically generated.
// Please do not edit these files manually.
//
// ------------------------------------------------

#nullable restore

using System;
using System.Linq;
using Elastic.Clients.Elasticsearch.Serialization;

namespace Elastic.Clients.Elasticsearch.Mapping;

[System.Text.Json.Serialization.JsonConverter(typeof(Elastic.Clients.Elasticsearch.Mapping.Json.DenseVectorElementTypeConverter))]
public enum DenseVectorElementType
{
	/// <include file="DenseVectorElementType.g.xml" path="doc/member[@key='_types.mapping.DenseVectorElementType#bit']/*"/>
	[System.Runtime.Serialization.EnumMember(Value = "bit")]
	Bit,
	/// <include file="DenseVectorElementType.g.xml" path="doc/member[@key='_types.mapping.DenseVectorElementType#byte']/*"/>
	[System.Runtime.Serialization.EnumMember(Value = "byte")]
	Byte,
	/// <include file="DenseVectorElementType.g.xml" path="doc/member[@key='_types.mapping.DenseVectorElementType#float']/*"/>
	[System.Runtime.Serialization.EnumMember(Value = "float")]
	Float
}