// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.
//
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// ------------------------------------------------
//
// This file is automatically generated.
// Please do not edit these files manually.
//
// ------------------------------------------------

#nullable restore

using System;
using System.Linq;
using Elastic.Clients.Elasticsearch.Serialization;

namespace Elastic.Clients.Elasticsearch.Core.ReindexRethrottle;

/// <include file="../../../SpecReferences.xml" path="doc/member[@key='_global.reindex_rethrottle.ReindexStatus']/*"/>
[System.Text.Json.Serialization.JsonConverter(typeof(Elastic.Clients.Elasticsearch.Core.ReindexRethrottle.Json.ReindexStatusConverter))]
public sealed partial class ReindexStatus
{
	[System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
	public ReindexStatus(long batches, long created, long deleted, long noops, float requestsPerSecond, Elastic.Clients.Elasticsearch.Retries retries, System.TimeSpan throttledMillis, System.TimeSpan throttledUntilMillis, long total, long updated, long versionConflicts)
	{
		Batches = batches;
		Created = created;
		Deleted = deleted;
		Noops = noops;
		RequestsPerSecond = requestsPerSecond;
		Retries = retries;
		ThrottledMillis = throttledMillis;
		ThrottledUntilMillis = throttledUntilMillis;
		Total = total;
		Updated = updated;
		VersionConflicts = versionConflicts;
	}

	public ReindexStatus()
	{
	}

	[System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
	internal ReindexStatus(Elastic.Clients.Elasticsearch.Serialization.JsonConstructorSentinel sentinel)
	{
		_ = sentinel;
	}

	/// <include file="ReindexStatus.g.xml" path="doc/member[@key='_global.reindex_rethrottle.ReindexStatus#batches']/*"/>
	public required long Batches { get; set; }

	/// <include file="ReindexStatus.g.xml" path="doc/member[@key='_global.reindex_rethrottle.ReindexStatus#created']/*"/>
	public required long Created { get; set; }

	/// <include file="ReindexStatus.g.xml" path="doc/member[@key='_global.reindex_rethrottle.ReindexStatus#deleted']/*"/>
	public required long Deleted { get; set; }

	/// <include file="ReindexStatus.g.xml" path="doc/member[@key='_global.reindex_rethrottle.ReindexStatus#noops']/*"/>
	public required long Noops { get; set; }

	/// <include file="ReindexStatus.g.xml" path="doc/member[@key='_global.reindex_rethrottle.ReindexStatus#requests_per_second']/*"/>
	public required float RequestsPerSecond { get; set; }

	/// <include file="ReindexStatus.g.xml" path="doc/member[@key='_global.reindex_rethrottle.ReindexStatus#retries']/*"/>
	public required Elastic.Clients.Elasticsearch.Retries Retries { get; set; }
	public Elastic.Clients.Elasticsearch.Duration? Throttled { get; set; }

	/// <include file="ReindexStatus.g.xml" path="doc/member[@key='_global.reindex_rethrottle.ReindexStatus#throttled_millis']/*"/>
	public required System.TimeSpan ThrottledMillis { get; set; }
	public Elastic.Clients.Elasticsearch.Duration? ThrottledUntil { get; set; }

	/// <include file="ReindexStatus.g.xml" path="doc/member[@key='_global.reindex_rethrottle.ReindexStatus#throttled_until_millis']/*"/>
	public required System.TimeSpan ThrottledUntilMillis { get; set; }

	/// <include file="ReindexStatus.g.xml" path="doc/member[@key='_global.reindex_rethrottle.ReindexStatus#total']/*"/>
	public required long Total { get; set; }

	/// <include file="ReindexStatus.g.xml" path="doc/member[@key='_global.reindex_rethrottle.ReindexStatus#updated']/*"/>
	public required long Updated { get; set; }

	/// <include file="ReindexStatus.g.xml" path="doc/member[@key='_global.reindex_rethrottle.ReindexStatus#version_conflicts']/*"/>
	public required long VersionConflicts { get; set; }
}