steps:
  - label: ":dotnet: Elasticsearch-Net {{ matrix.suite }}"
    agents:
      provider: "gcp"
    env:
      TEST_SUITE: "{{ matrix.suite }}"
      STACK_VERSION: master-SNAPSHOT
      DOTNET_VERSION: 9.0.100
    matrix:
      setup:
        suite:
          - "free"
          - "platinum"
    command: ./.buildkite/run-tests
