// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.
//
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// ------------------------------------------------
//
// This file is automatically generated.
// Please do not edit these files manually.
//
// ------------------------------------------------

#nullable restore

using System;
using System.Linq;
using Elastic.Clients.Elasticsearch.Serialization;

namespace Elastic.Clients.Elasticsearch.IndexManagement;

/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request']/*"/>
/// <include file="../../SpecReferences.xml" path="doc/member[@key='indices.put_index_template.Request']/*"/>
public sealed partial class PutIndexTemplateRequestParameters : Elastic.Transport.RequestParameters
{
	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#cause']/*"/>
	public string? Cause { get => Q<string?>("cause"); set => Q("cause", value); }

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#create']/*"/>
	public bool? Create { get => Q<bool?>("create"); set => Q("create", value); }

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#master_timeout']/*"/>
	public Elastic.Clients.Elasticsearch.Duration? MasterTimeout { get => Q<Elastic.Clients.Elasticsearch.Duration?>("master_timeout"); set => Q("master_timeout", value); }
}

/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request']/*"/>
/// <include file="../../SpecReferences.xml" path="doc/member[@key='indices.put_index_template.Request']/*"/>
[System.Text.Json.Serialization.JsonConverter(typeof(Elastic.Clients.Elasticsearch.IndexManagement.Json.PutIndexTemplateRequestConverter))]
public sealed partial class PutIndexTemplateRequest : Elastic.Clients.Elasticsearch.Requests.PlainRequest<Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestParameters>
{
	[System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
	public PutIndexTemplateRequest(Elastic.Clients.Elasticsearch.Name name) : base(r => r.Required("name", name))
	{
	}

	public PutIndexTemplateRequest()
	{
	}

	[System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
	internal PutIndexTemplateRequest(Elastic.Clients.Elasticsearch.Serialization.JsonConstructorSentinel sentinel)
	{
		_ = sentinel;
	}

	internal override Elastic.Clients.Elasticsearch.Requests.ApiUrls ApiUrls => Elastic.Clients.Elasticsearch.Requests.ApiUrlLookup.IndexManagementPutIndexTemplate;

	protected override Elastic.Transport.HttpMethod StaticHttpMethod => Elastic.Transport.HttpMethod.PUT;

	internal override bool SupportsBody => true;

	internal override string OperationName => "indices.put_index_template";

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#name']/*"/>
	public required Elastic.Clients.Elasticsearch.Name Name { get => P<Elastic.Clients.Elasticsearch.Name>("name"); set => PR("name", value); }

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#cause']/*"/>
	public string? Cause { get => Q<string?>("cause"); set => Q("cause", value); }

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#create']/*"/>
	public bool? Create { get => Q<bool?>("create"); set => Q("create", value); }

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#master_timeout']/*"/>
	public Elastic.Clients.Elasticsearch.Duration? MasterTimeout { get => Q<Elastic.Clients.Elasticsearch.Duration?>("master_timeout"); set => Q("master_timeout", value); }

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#allow_auto_create']/*"/>
	public bool? AllowAutoCreate { get; set; }

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#composed_of']/*"/>
	public System.Collections.Generic.ICollection<Elastic.Clients.Elasticsearch.Name>? ComposedOf { get; set; }

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#data_stream']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.DataStreamVisibility? DataStream { get; set; }

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#deprecated']/*"/>
	public bool? Deprecated { get; set; }

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#ignore_missing_component_templates']/*"/>
	public System.Collections.Generic.ICollection<string>? IgnoreMissingComponentTemplates { get; set; }

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#index_patterns']/*"/>
	public Elastic.Clients.Elasticsearch.Indices? IndexPatterns { get; set; }

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#_meta']/*"/>
	public System.Collections.Generic.IDictionary<string, object>? Meta { get; set; }

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#priority']/*"/>
	public long? Priority { get; set; }

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#template']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.IndexTemplateMapping? Template { get; set; }

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#version']/*"/>
	public long? Version { get; set; }
}

/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request']/*"/>
/// <include file="../../SpecReferences.xml" path="doc/member[@key='indices.put_index_template.Request']/*"/>
public readonly partial struct PutIndexTemplateRequestDescriptor
{
	internal Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequest Instance { get; init; }

	[System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
	public PutIndexTemplateRequestDescriptor(Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequest instance)
	{
		Instance = instance;
	}

	public PutIndexTemplateRequestDescriptor(Elastic.Clients.Elasticsearch.Name name)
	{
		Instance = new Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequest(name);
	}

	[System.Obsolete("The use of the parameterless constructor is not permitted for this type.")]
	public PutIndexTemplateRequestDescriptor()
	{
		throw new System.InvalidOperationException("The use of the parameterless constructor is not permitted for this type.");
	}

	public static explicit operator Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor(Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequest instance) => new Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor(instance);
	public static implicit operator Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequest(Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor descriptor) => descriptor.Instance;

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#name']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor Name(Elastic.Clients.Elasticsearch.Name value)
	{
		Instance.Name = value;
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#cause']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor Cause(string? value)
	{
		Instance.Cause = value;
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#create']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor Create(bool? value = true)
	{
		Instance.Create = value;
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#master_timeout']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor MasterTimeout(Elastic.Clients.Elasticsearch.Duration? value)
	{
		Instance.MasterTimeout = value;
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#allow_auto_create']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor AllowAutoCreate(bool? value = true)
	{
		Instance.AllowAutoCreate = value;
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#composed_of']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor ComposedOf(System.Collections.Generic.ICollection<Elastic.Clients.Elasticsearch.Name>? value)
	{
		Instance.ComposedOf = value;
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#composed_of']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor ComposedOf(params Elastic.Clients.Elasticsearch.Name[] values)
	{
		Instance.ComposedOf = [.. values];
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#data_stream']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor DataStream(Elastic.Clients.Elasticsearch.IndexManagement.DataStreamVisibility? value)
	{
		Instance.DataStream = value;
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#data_stream']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor DataStream()
	{
		Instance.DataStream = Elastic.Clients.Elasticsearch.IndexManagement.DataStreamVisibilityDescriptor.Build(null);
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#data_stream']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor DataStream(System.Action<Elastic.Clients.Elasticsearch.IndexManagement.DataStreamVisibilityDescriptor>? action)
	{
		Instance.DataStream = Elastic.Clients.Elasticsearch.IndexManagement.DataStreamVisibilityDescriptor.Build(action);
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#deprecated']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor Deprecated(bool? value = true)
	{
		Instance.Deprecated = value;
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#ignore_missing_component_templates']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor IgnoreMissingComponentTemplates(System.Collections.Generic.ICollection<string>? value)
	{
		Instance.IgnoreMissingComponentTemplates = value;
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#ignore_missing_component_templates']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor IgnoreMissingComponentTemplates(params string[] values)
	{
		Instance.IgnoreMissingComponentTemplates = [.. values];
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#index_patterns']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor IndexPatterns(Elastic.Clients.Elasticsearch.Indices? value)
	{
		Instance.IndexPatterns = value;
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#_meta']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor Meta(System.Collections.Generic.IDictionary<string, object>? value)
	{
		Instance.Meta = value;
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#_meta']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor Meta()
	{
		Instance.Meta = Elastic.Clients.Elasticsearch.Fluent.FluentDictionaryOfStringObject.Build(null);
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#_meta']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor Meta(System.Action<Elastic.Clients.Elasticsearch.Fluent.FluentDictionaryOfStringObject>? action)
	{
		Instance.Meta = Elastic.Clients.Elasticsearch.Fluent.FluentDictionaryOfStringObject.Build(action);
		return this;
	}

	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor AddMeta(string key, object value)
	{
		Instance.Meta ??= new System.Collections.Generic.Dictionary<string, object>();
		Instance.Meta.Add(key, value);
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#priority']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor Priority(long? value)
	{
		Instance.Priority = value;
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#template']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor Template(Elastic.Clients.Elasticsearch.IndexManagement.IndexTemplateMapping? value)
	{
		Instance.Template = value;
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#template']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor Template()
	{
		Instance.Template = Elastic.Clients.Elasticsearch.IndexManagement.IndexTemplateMappingDescriptor.Build(null);
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#template']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor Template(System.Action<Elastic.Clients.Elasticsearch.IndexManagement.IndexTemplateMappingDescriptor>? action)
	{
		Instance.Template = Elastic.Clients.Elasticsearch.IndexManagement.IndexTemplateMappingDescriptor.Build(action);
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#template']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor Template<T>(System.Action<Elastic.Clients.Elasticsearch.IndexManagement.IndexTemplateMappingDescriptor<T>>? action)
	{
		Instance.Template = Elastic.Clients.Elasticsearch.IndexManagement.IndexTemplateMappingDescriptor<T>.Build(action);
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#version']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor Version(long? value)
	{
		Instance.Version = value;
		return this;
	}

	[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	internal static Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequest Build(System.Action<Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor> action)
	{
		var builder = new Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor(new Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequest(Elastic.Clients.Elasticsearch.Serialization.JsonConstructorSentinel.Instance));
		action.Invoke(builder);
		return builder.Instance;
	}

	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor ErrorTrace(bool? value)
	{
		Instance.ErrorTrace = value;
		return this;
	}

	[System.Diagnostics.CodeAnalysis.Experimental("ESEXP0001", UrlFormat = "https://www.elastic.co/docs/reference/elasticsearch/clients/dotnet/experimental#{0}"
#if NET10_0_OR_GREATER
	, Message = "Use of response filtering can result in a response from Elasticsearch that cannot be correctly deserialized to the respective response type for the request."
#endif
	)]
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor FilterPath(params string[]? value)
	{
		Instance.FilterPath = value;
		return this;
	}

	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor Human(bool? value)
	{
		Instance.Human = value;
		return this;
	}

	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor Pretty(bool? value)
	{
		Instance.Pretty = value;
		return this;
	}

	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor SourceQueryString(string? value)
	{
		Instance.SourceQueryString = value;
		return this;
	}

	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor RequestConfiguration(Elastic.Transport.IRequestConfiguration? value)
	{
		Instance.RequestConfiguration = value;
		return this;
	}

	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor RequestConfiguration(System.Func<Elastic.Transport.RequestConfigurationDescriptor, Elastic.Transport.IRequestConfiguration>? configurationSelector)
	{
		Instance.RequestConfiguration = configurationSelector.Invoke(Instance.RequestConfiguration is null ? new Elastic.Transport.RequestConfigurationDescriptor() : new Elastic.Transport.RequestConfigurationDescriptor(Instance.RequestConfiguration)) ?? Instance.RequestConfiguration;
		return this;
	}
}

/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request']/*"/>
/// <include file="../../SpecReferences.xml" path="doc/member[@key='indices.put_index_template.Request']/*"/>
public readonly partial struct PutIndexTemplateRequestDescriptor<TDocument>
{
	internal Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequest Instance { get; init; }

	[System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
	public PutIndexTemplateRequestDescriptor(Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequest instance)
	{
		Instance = instance;
	}

	public PutIndexTemplateRequestDescriptor(Elastic.Clients.Elasticsearch.Name name)
	{
		Instance = new Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequest(name);
	}

	[System.Obsolete("The use of the parameterless constructor is not permitted for this type.")]
	public PutIndexTemplateRequestDescriptor()
	{
		throw new System.InvalidOperationException("The use of the parameterless constructor is not permitted for this type.");
	}

	public static explicit operator Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor<TDocument>(Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequest instance) => new Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor<TDocument>(instance);
	public static implicit operator Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequest(Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor<TDocument> descriptor) => descriptor.Instance;

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#name']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor<TDocument> Name(Elastic.Clients.Elasticsearch.Name value)
	{
		Instance.Name = value;
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#cause']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor<TDocument> Cause(string? value)
	{
		Instance.Cause = value;
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#create']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor<TDocument> Create(bool? value = true)
	{
		Instance.Create = value;
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#master_timeout']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor<TDocument> MasterTimeout(Elastic.Clients.Elasticsearch.Duration? value)
	{
		Instance.MasterTimeout = value;
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#allow_auto_create']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor<TDocument> AllowAutoCreate(bool? value = true)
	{
		Instance.AllowAutoCreate = value;
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#composed_of']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor<TDocument> ComposedOf(System.Collections.Generic.ICollection<Elastic.Clients.Elasticsearch.Name>? value)
	{
		Instance.ComposedOf = value;
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#composed_of']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor<TDocument> ComposedOf(params Elastic.Clients.Elasticsearch.Name[] values)
	{
		Instance.ComposedOf = [.. values];
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#data_stream']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor<TDocument> DataStream(Elastic.Clients.Elasticsearch.IndexManagement.DataStreamVisibility? value)
	{
		Instance.DataStream = value;
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#data_stream']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor<TDocument> DataStream()
	{
		Instance.DataStream = Elastic.Clients.Elasticsearch.IndexManagement.DataStreamVisibilityDescriptor.Build(null);
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#data_stream']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor<TDocument> DataStream(System.Action<Elastic.Clients.Elasticsearch.IndexManagement.DataStreamVisibilityDescriptor>? action)
	{
		Instance.DataStream = Elastic.Clients.Elasticsearch.IndexManagement.DataStreamVisibilityDescriptor.Build(action);
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#deprecated']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor<TDocument> Deprecated(bool? value = true)
	{
		Instance.Deprecated = value;
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#ignore_missing_component_templates']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor<TDocument> IgnoreMissingComponentTemplates(System.Collections.Generic.ICollection<string>? value)
	{
		Instance.IgnoreMissingComponentTemplates = value;
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#ignore_missing_component_templates']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor<TDocument> IgnoreMissingComponentTemplates(params string[] values)
	{
		Instance.IgnoreMissingComponentTemplates = [.. values];
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#index_patterns']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor<TDocument> IndexPatterns(Elastic.Clients.Elasticsearch.Indices? value)
	{
		Instance.IndexPatterns = value;
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#_meta']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor<TDocument> Meta(System.Collections.Generic.IDictionary<string, object>? value)
	{
		Instance.Meta = value;
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#_meta']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor<TDocument> Meta()
	{
		Instance.Meta = Elastic.Clients.Elasticsearch.Fluent.FluentDictionaryOfStringObject.Build(null);
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#_meta']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor<TDocument> Meta(System.Action<Elastic.Clients.Elasticsearch.Fluent.FluentDictionaryOfStringObject>? action)
	{
		Instance.Meta = Elastic.Clients.Elasticsearch.Fluent.FluentDictionaryOfStringObject.Build(action);
		return this;
	}

	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor<TDocument> AddMeta(string key, object value)
	{
		Instance.Meta ??= new System.Collections.Generic.Dictionary<string, object>();
		Instance.Meta.Add(key, value);
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#priority']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor<TDocument> Priority(long? value)
	{
		Instance.Priority = value;
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#template']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor<TDocument> Template(Elastic.Clients.Elasticsearch.IndexManagement.IndexTemplateMapping? value)
	{
		Instance.Template = value;
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#template']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor<TDocument> Template()
	{
		Instance.Template = Elastic.Clients.Elasticsearch.IndexManagement.IndexTemplateMappingDescriptor<TDocument>.Build(null);
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#template']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor<TDocument> Template(System.Action<Elastic.Clients.Elasticsearch.IndexManagement.IndexTemplateMappingDescriptor<TDocument>>? action)
	{
		Instance.Template = Elastic.Clients.Elasticsearch.IndexManagement.IndexTemplateMappingDescriptor<TDocument>.Build(action);
		return this;
	}

	/// <include file="PutIndexTemplateRequest.g.xml" path="doc/member[@key='indices.put_index_template.Request#version']/*"/>
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor<TDocument> Version(long? value)
	{
		Instance.Version = value;
		return this;
	}

	[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	internal static Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequest Build(System.Action<Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor<TDocument>> action)
	{
		var builder = new Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor<TDocument>(new Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequest(Elastic.Clients.Elasticsearch.Serialization.JsonConstructorSentinel.Instance));
		action.Invoke(builder);
		return builder.Instance;
	}

	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor<TDocument> ErrorTrace(bool? value)
	{
		Instance.ErrorTrace = value;
		return this;
	}

	[System.Diagnostics.CodeAnalysis.Experimental("ESEXP0001", UrlFormat = "https://www.elastic.co/docs/reference/elasticsearch/clients/dotnet/experimental#{0}"
#if NET10_0_OR_GREATER
	, Message = "Use of response filtering can result in a response from Elasticsearch that cannot be correctly deserialized to the respective response type for the request."
#endif
	)]
	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor<TDocument> FilterPath(params string[]? value)
	{
		Instance.FilterPath = value;
		return this;
	}

	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor<TDocument> Human(bool? value)
	{
		Instance.Human = value;
		return this;
	}

	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor<TDocument> Pretty(bool? value)
	{
		Instance.Pretty = value;
		return this;
	}

	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor<TDocument> SourceQueryString(string? value)
	{
		Instance.SourceQueryString = value;
		return this;
	}

	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor<TDocument> RequestConfiguration(Elastic.Transport.IRequestConfiguration? value)
	{
		Instance.RequestConfiguration = value;
		return this;
	}

	public Elastic.Clients.Elasticsearch.IndexManagement.PutIndexTemplateRequestDescriptor<TDocument> RequestConfiguration(System.Func<Elastic.Transport.RequestConfigurationDescriptor, Elastic.Transport.IRequestConfiguration>? configurationSelector)
	{
		Instance.RequestConfiguration = configurationSelector.Invoke(Instance.RequestConfiguration is null ? new Elastic.Transport.RequestConfigurationDescriptor() : new Elastic.Transport.RequestConfigurationDescriptor(Instance.RequestConfiguration)) ?? Instance.RequestConfiguration;
		return this;
	}
}