// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.
//
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// ------------------------------------------------
//
// This file is automatically generated.
// Please do not edit these files manually.
//
// ------------------------------------------------

#nullable restore

using System;
using System.Linq;
using Elastic.Clients.Elasticsearch.Serialization;

namespace Elastic.Clients.Elasticsearch.MachineLearning;

/// <include file="GetCategoriesRequest.g.xml" path="doc/member[@key='ml.get_categories.Request']/*"/>
/// <include file="../../SpecReferences.xml" path="doc/member[@key='ml.get_categories.Request']/*"/>
public sealed partial class GetCategoriesRequestParameters : Elastic.Transport.RequestParameters
{
	/// <include file="GetCategoriesRequest.g.xml" path="doc/member[@key='ml.get_categories.Request#from']/*"/>
	public int? From { get => Q<int?>("from"); set => Q("from", value); }

	/// <include file="GetCategoriesRequest.g.xml" path="doc/member[@key='ml.get_categories.Request#partition_field_value']/*"/>
	public string? PartitionFieldValue { get => Q<string?>("partition_field_value"); set => Q("partition_field_value", value); }

	/// <include file="GetCategoriesRequest.g.xml" path="doc/member[@key='ml.get_categories.Request#size']/*"/>
	public int? Size { get => Q<int?>("size"); set => Q("size", value); }
}

/// <include file="GetCategoriesRequest.g.xml" path="doc/member[@key='ml.get_categories.Request']/*"/>
/// <include file="../../SpecReferences.xml" path="doc/member[@key='ml.get_categories.Request']/*"/>
[System.Text.Json.Serialization.JsonConverter(typeof(Elastic.Clients.Elasticsearch.MachineLearning.Json.GetCategoriesRequestConverter))]
public sealed partial class GetCategoriesRequest : Elastic.Clients.Elasticsearch.Requests.PlainRequest<Elastic.Clients.Elasticsearch.MachineLearning.GetCategoriesRequestParameters>
{
	[System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
	public GetCategoriesRequest(Elastic.Clients.Elasticsearch.Id jobId, string? categoryId) : base(r => r.Required("job_id", jobId).Optional("category_id", categoryId))
	{
	}

	[System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
	public GetCategoriesRequest(Elastic.Clients.Elasticsearch.Id jobId) : base(r => r.Required("job_id", jobId))
	{
	}

	public GetCategoriesRequest()
	{
	}

	[System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
	internal GetCategoriesRequest(Elastic.Clients.Elasticsearch.Serialization.JsonConstructorSentinel sentinel)
	{
		_ = sentinel;
	}

	internal override Elastic.Clients.Elasticsearch.Requests.ApiUrls ApiUrls => Elastic.Clients.Elasticsearch.Requests.ApiUrlLookup.MachineLearningGetCategories;

	protected override Elastic.Transport.HttpMethod StaticHttpMethod => Elastic.Transport.HttpMethod.POST;

	internal override bool SupportsBody => true;

	internal override string OperationName => "ml.get_categories";

	/// <include file="GetCategoriesRequest.g.xml" path="doc/member[@key='ml.get_categories.Request#category_id']/*"/>
	public string? CategoryId { get => P<string?>("category_id"); set => PO("category_id", value); }

	/// <include file="GetCategoriesRequest.g.xml" path="doc/member[@key='ml.get_categories.Request#job_id']/*"/>
	public required Elastic.Clients.Elasticsearch.Id JobId { get => P<Elastic.Clients.Elasticsearch.Id>("job_id"); set => PR("job_id", value); }

	/// <include file="GetCategoriesRequest.g.xml" path="doc/member[@key='ml.get_categories.Request#from']/*"/>
	public int? From { get => Q<int?>("from"); set => Q("from", value); }

	/// <include file="GetCategoriesRequest.g.xml" path="doc/member[@key='ml.get_categories.Request#partition_field_value']/*"/>
	public string? PartitionFieldValue { get => Q<string?>("partition_field_value"); set => Q("partition_field_value", value); }

	/// <include file="GetCategoriesRequest.g.xml" path="doc/member[@key='ml.get_categories.Request#size']/*"/>
	public int? Size { get => Q<int?>("size"); set => Q("size", value); }

	/// <include file="GetCategoriesRequest.g.xml" path="doc/member[@key='ml.get_categories.Request#page']/*"/>
	public Elastic.Clients.Elasticsearch.MachineLearning.Page? Page { get; set; }
}

/// <include file="GetCategoriesRequest.g.xml" path="doc/member[@key='ml.get_categories.Request']/*"/>
/// <include file="../../SpecReferences.xml" path="doc/member[@key='ml.get_categories.Request']/*"/>
public readonly partial struct GetCategoriesRequestDescriptor
{
	internal Elastic.Clients.Elasticsearch.MachineLearning.GetCategoriesRequest Instance { get; init; }

	[System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
	public GetCategoriesRequestDescriptor(Elastic.Clients.Elasticsearch.MachineLearning.GetCategoriesRequest instance)
	{
		Instance = instance;
	}

	public GetCategoriesRequestDescriptor(Elastic.Clients.Elasticsearch.Id jobId, string? categoryId)
	{
		Instance = new Elastic.Clients.Elasticsearch.MachineLearning.GetCategoriesRequest(jobId, categoryId);
	}

	public GetCategoriesRequestDescriptor(Elastic.Clients.Elasticsearch.Id jobId)
	{
		Instance = new Elastic.Clients.Elasticsearch.MachineLearning.GetCategoriesRequest(jobId);
	}

	[System.Obsolete("The use of the parameterless constructor is not permitted for this type.")]
	public GetCategoriesRequestDescriptor()
	{
		throw new System.InvalidOperationException("The use of the parameterless constructor is not permitted for this type.");
	}

	public static explicit operator Elastic.Clients.Elasticsearch.MachineLearning.GetCategoriesRequestDescriptor(Elastic.Clients.Elasticsearch.MachineLearning.GetCategoriesRequest instance) => new Elastic.Clients.Elasticsearch.MachineLearning.GetCategoriesRequestDescriptor(instance);
	public static implicit operator Elastic.Clients.Elasticsearch.MachineLearning.GetCategoriesRequest(Elastic.Clients.Elasticsearch.MachineLearning.GetCategoriesRequestDescriptor descriptor) => descriptor.Instance;

	/// <include file="GetCategoriesRequest.g.xml" path="doc/member[@key='ml.get_categories.Request#category_id']/*"/>
	public Elastic.Clients.Elasticsearch.MachineLearning.GetCategoriesRequestDescriptor CategoryId(string? value)
	{
		Instance.CategoryId = value;
		return this;
	}

	/// <include file="GetCategoriesRequest.g.xml" path="doc/member[@key='ml.get_categories.Request#job_id']/*"/>
	public Elastic.Clients.Elasticsearch.MachineLearning.GetCategoriesRequestDescriptor JobId(Elastic.Clients.Elasticsearch.Id value)
	{
		Instance.JobId = value;
		return this;
	}

	/// <include file="GetCategoriesRequest.g.xml" path="doc/member[@key='ml.get_categories.Request#from']/*"/>
	public Elastic.Clients.Elasticsearch.MachineLearning.GetCategoriesRequestDescriptor From(int? value)
	{
		Instance.From = value;
		return this;
	}

	/// <include file="GetCategoriesRequest.g.xml" path="doc/member[@key='ml.get_categories.Request#partition_field_value']/*"/>
	public Elastic.Clients.Elasticsearch.MachineLearning.GetCategoriesRequestDescriptor PartitionFieldValue(string? value)
	{
		Instance.PartitionFieldValue = value;
		return this;
	}

	/// <include file="GetCategoriesRequest.g.xml" path="doc/member[@key='ml.get_categories.Request#size']/*"/>
	public Elastic.Clients.Elasticsearch.MachineLearning.GetCategoriesRequestDescriptor Size(int? value)
	{
		Instance.Size = value;
		return this;
	}

	/// <include file="GetCategoriesRequest.g.xml" path="doc/member[@key='ml.get_categories.Request#page']/*"/>
	public Elastic.Clients.Elasticsearch.MachineLearning.GetCategoriesRequestDescriptor Page(Elastic.Clients.Elasticsearch.MachineLearning.Page? value)
	{
		Instance.Page = value;
		return this;
	}

	/// <include file="GetCategoriesRequest.g.xml" path="doc/member[@key='ml.get_categories.Request#page']/*"/>
	public Elastic.Clients.Elasticsearch.MachineLearning.GetCategoriesRequestDescriptor Page()
	{
		Instance.Page = Elastic.Clients.Elasticsearch.MachineLearning.PageDescriptor.Build(null);
		return this;
	}

	/// <include file="GetCategoriesRequest.g.xml" path="doc/member[@key='ml.get_categories.Request#page']/*"/>
	public Elastic.Clients.Elasticsearch.MachineLearning.GetCategoriesRequestDescriptor Page(System.Action<Elastic.Clients.Elasticsearch.MachineLearning.PageDescriptor>? action)
	{
		Instance.Page = Elastic.Clients.Elasticsearch.MachineLearning.PageDescriptor.Build(action);
		return this;
	}

	[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	internal static Elastic.Clients.Elasticsearch.MachineLearning.GetCategoriesRequest Build(System.Action<Elastic.Clients.Elasticsearch.MachineLearning.GetCategoriesRequestDescriptor> action)
	{
		var builder = new Elastic.Clients.Elasticsearch.MachineLearning.GetCategoriesRequestDescriptor(new Elastic.Clients.Elasticsearch.MachineLearning.GetCategoriesRequest(Elastic.Clients.Elasticsearch.Serialization.JsonConstructorSentinel.Instance));
		action.Invoke(builder);
		return builder.Instance;
	}

	public Elastic.Clients.Elasticsearch.MachineLearning.GetCategoriesRequestDescriptor ErrorTrace(bool? value)
	{
		Instance.ErrorTrace = value;
		return this;
	}

	[System.Diagnostics.CodeAnalysis.Experimental("ESEXP0001", UrlFormat = "https://www.elastic.co/docs/reference/elasticsearch/clients/dotnet/experimental#{0}"
#if NET10_0_OR_GREATER
	, Message = "Use of response filtering can result in a response from Elasticsearch that cannot be correctly deserialized to the respective response type for the request."
#endif
	)]
	public Elastic.Clients.Elasticsearch.MachineLearning.GetCategoriesRequestDescriptor FilterPath(params string[]? value)
	{
		Instance.FilterPath = value;
		return this;
	}

	public Elastic.Clients.Elasticsearch.MachineLearning.GetCategoriesRequestDescriptor Human(bool? value)
	{
		Instance.Human = value;
		return this;
	}

	public Elastic.Clients.Elasticsearch.MachineLearning.GetCategoriesRequestDescriptor Pretty(bool? value)
	{
		Instance.Pretty = value;
		return this;
	}

	public Elastic.Clients.Elasticsearch.MachineLearning.GetCategoriesRequestDescriptor SourceQueryString(string? value)
	{
		Instance.SourceQueryString = value;
		return this;
	}

	public Elastic.Clients.Elasticsearch.MachineLearning.GetCategoriesRequestDescriptor RequestConfiguration(Elastic.Transport.IRequestConfiguration? value)
	{
		Instance.RequestConfiguration = value;
		return this;
	}

	public Elastic.Clients.Elasticsearch.MachineLearning.GetCategoriesRequestDescriptor RequestConfiguration(System.Func<Elastic.Transport.RequestConfigurationDescriptor, Elastic.Transport.IRequestConfiguration>? configurationSelector)
	{
		Instance.RequestConfiguration = configurationSelector.Invoke(Instance.RequestConfiguration is null ? new Elastic.Transport.RequestConfigurationDescriptor() : new Elastic.Transport.RequestConfigurationDescriptor(Instance.RequestConfiguration)) ?? Instance.RequestConfiguration;
		return this;
	}
}