[[release-notes-8.0.9]]
== Release notes v8.0.9

[discrete]
=== Bug fixes

- https://github.com/elastic/elasticsearch-net/pull/7446[#7446] Fix byte properties 
in index stats types. (issue: https://github.com/elastic/elasticsearch-net/issues/7445[#7445])

[discrete]
=== Enhancements

- https://github.com/elastic/elasticsearch-net/pull/7467[#7467] Source serialization 
always sends fractional format for double and floats. (issue: https://github.com/elastic/elasticsearch-net/issues/7051[#7051])

[discrete]
=== Breaking changes

[discrete]
==== Source serialization of float and double properties

By default, when serializing `double` and `float` properties, the `System.Text.Json` 
serializer uses the "G17" format when serializing double types. This format omits 
the decimal point and/or trailing zeros if they are not required for the data to 
roundtrip. This is generally correct, as JSON doesn't specify a type for numbers.

However, in the case of source serialization, mappings for numeric properties may 
be incorrectly inferred if trailing zeros are omitted. In this release, we have 
included a new custom converter for `float` and `double` types when serialized using
the default source serializer. These converters ensure that at least one precision 
digit is included after a decimal point, even for round numbers.

You may therefore observe changes to the serialized source document after 
upgrading to this version.