[[release-notes-8.0.1]]
== Release notes v8.0.1

[discrete]
=== Bug fixes

- Fix MultiSearchTemplateRequest serialization (issue: 
https://github.com/elastic/elasticsearch-net/issues/7006[#7006])

[discrete]
=== Breaking changes

This release includes the following breaking changes:

[discrete]
==== MultiSearchTemplate type changes

The `Core.MSearchTemplate.RequestItem` type has been renamed to
`Core.MSearchTemplate.SearchTemplateRequestItem`. It no longer derives from the 
`Union<T1, T2>` type. It has been manually designed to support serialisation to 
NDJSON, as required by the MSearchTemplate endpoint.

The `MultiSearchTemplateRequest.SearchTemplates` property has been updated to 
use this newly defined type.

This breaking change has been included in this patch release due to the 
original code-generated type not functioning correctly and therefore we have 
determined that this should ship ASAP.

[discrete]
=== MultiSearch type changes

The `Core.MSearch.SearchRequestItem` type has been sealed for consistency with 
the design choices in the rest of the client. While technically breaking, we 
have decided that this should be included in this release before any potential 
derived types may exist in consuming applications.