:ref_current: https://www.elastic.co/guide/en/elasticsearch/reference/7.10

:github: https://github.com/elastic/elasticsearch-net

:nuget: https://www.nuget.org/packages

////
IMPORTANT NOTE
==============
This file has been generated from https://github.com/elastic/elasticsearch-net/tree/7.x/src/Tests/Tests/QueryDsl/Specialized/Pinned/PinnedQueryUsageTests.cs. 
If you wish to submit a PR for any spelling mistakes, typos or grammatical errors for this file,
please modify the original csharp file found at the link and submit the PR with that change. Thanks!
////

[[pinned-query-usage]]
=== Pinned Query Usage

Promotes selected documents to rank higher than those matching a given query. This feature is typically used to
guide searchers to curated documents that are promoted over and above any "organic" matches for a search. The promoted or "pinned"
documents are identified using the document IDs stored in the _id field.
See the Elasticsearch documentation on {ref_current}/query-dsl-pinned-query.html[pinned query] for more details.

==== Fluent DSL example

[source,csharp]
----
q
.Pinned(c => c
    .Name("named_query")
    .Boost(1.1)
    .Organic(qq => qq.MatchAll(m => m.Name("organic_query")))
    .Ids(1, 11, 22)
)
----

==== Object Initializer syntax example

[source,csharp]
----
new PinnedQuery()
{
    Name = "named_query",
    Boost = 1.1,
    Organic = new MatchAllQuery { Name = "organic_query" },
    Ids = new Id[] { 1,11,22 },
}
----

[source,javascript]
.Example json output
----
{
  "pinned": {
    "_name": "named_query",
    "boost": 1.1,
    "organic": {
      "match_all": {
        "_name": "organic_query"
      }
    },
    "ids": [
      1,
      11,
      22
    ]
  }
}
----

