:ref_current: https://www.elastic.co/guide/en/elasticsearch/reference/7.10

:github: https://github.com/elastic/elasticsearch-net

:nuget: https://www.nuget.org/packages

////
IMPORTANT NOTE
==============
This file has been generated from https://github.com/elastic/elasticsearch-net/tree/7.x/src/Tests/Tests/Search/Request/FieldsUsageTests.cs. 
If you wish to submit a PR for any spelling mistakes, typos or grammatical errors for this file,
please modify the original csharp file found at the link and submit the PR with that change. Thanks!
////

[[fields-usage]]
== Fields Usage

Allows to selectively load specific stored fields for each document represented by a search hit.

WARNING: The `fields` parameter is about fields that are explicitly marked as stored in the mapping,
which is off by default and generally not recommended.
Use <<source-filtering-usage,source filtering>> instead to select subsets of the original source document to be returned.

See the Elasticsearch documentation on {ref_current}/search-request-body.html#request-body-search-stored-fields[Fields] for more detail.

[float]
=== Fluent DSL example

[source,csharp]
----
s => s
.Query(q => ProjectFilter)
.StoredFields(fs => fs
    .Field(p => p.Name)
    .Field(p => p.StartedOn)
    .Field(p => p.NumberOfCommits)
    .Field(p => p.NumberOfContributors)
    .Field(p => p.DateString)
)
----

[float]
=== Object Initializer syntax example

[source,csharp]
----
new SearchRequest<Project>
{
    Query = ProjectFilter,
    StoredFields = Fields<Project>(
        p => p.Name,
        p => p.StartedOn,
        p => p.NumberOfCommits,
        p => p.NumberOfContributors,
        p => p.DateString)
}
----

[source,javascript]
.Example json output
----
{
  "query": {
    "term": {
      "type": {
        "value": "project"
      }
    }
  },
  "stored_fields": [
    "name",
    "startedOn",
    "numberOfCommits",
    "numberOfContributors",
    "dateString"
  ]
}
----

