:ref_current: https://www.elastic.co/guide/en/elasticsearch/reference/2.4

:xpack_current: https://www.elastic.co/guide/en/x-pack/2.4

:github: https://github.com/elastic/elasticsearch-net

:nuget: https://www.nuget.org/packages

////
IMPORTANT NOTE
==============
This file has been generated from https://github.com/elastic/elasticsearch-net/tree/2.x/src/Tests/Search/Request/ScriptFieldsUsageTests.cs. 
If you wish to submit a PR for any spelling mistakes, typos or grammatical errors for this file,
please modify the original csharp file found at the link and submit the PR with that change. Thanks!
////

[[script-fields-usage]]
== Script Fields Usage

Allows to return a script evaluation (based on different fields) for each hit.

Script fields can work on fields that are not stored, and allow to return custom values to 
be returned (the evaluated value of the script).

Script fields can also access the actual `_source` document and extract specific elements to 
be returned from it by using `params['_source']`.

See the Elasticsearch documentation on {ref_current}/search-request-script-fields.html[script fields] 
for more detail.

[float]
=== Fluent DSL example

[source,csharp]
----
s => s
.ScriptFields(sf=>sf
    .ScriptField("test1", sc=>sc
        .Inline("doc['my_field_name'].value * 2")
    )
    .ScriptField("test2", sc=>sc
        .Inline("doc['my_field_name'].value * factor")
        .Params(p=>p
            .Add("factor", 2.0)
        )
    )
)
----

[float]
=== Object Initializer syntax example

[source,csharp]
----
new SearchRequest<Project>
{
    ScriptFields = new ScriptFields
    {
        { "test1", new ScriptField
        {
            Script = new InlineScript("doc['my_field_name'].value * 2")
        } },
        { "test2", new InlineScript("doc['my_field_name'].value * factor")
        {
            Params = new FluentDictionary<string, object>
            {
                { "factor", 2.0 }
            }
        } }
    }
}
----

[source,javascript]
.Example json output
----
{
  "script_fields": {
    "test1": {
      "script": {
        "inline": "doc['my_field_name'].value * 2"
      }
    },
    "test2": {
      "script": {
        "inline": "doc['my_field_name'].value * factor",
        "params": {
          "factor": 2.0
        }
      }
    }
  }
}
----

