:ref_current: https://www.elastic.co/guide/en/elasticsearch/reference/7.10

:github: https://github.com/elastic/elasticsearch-net

:nuget: https://www.nuget.org/packages

////
IMPORTANT NOTE
==============
This file has been generated from https://github.com/elastic/elasticsearch-net/tree/7.x/src/Tests/Tests/Search/Request/ScriptFieldsUsageTests.cs. 
If you wish to submit a PR for any spelling mistakes, typos or grammatical errors for this file,
please modify the original csharp file found at the link and submit the PR with that change. Thanks!
////

[[script-fields-usage]]
== Script Fields Usage

Allows to return a script evaluation (based on different fields) for each hit.

Script fields can work on fields that are not stored, and allow to return custom values to
be returned (the evaluated value of the script).

Script fields can also access the actual `_source` document and extract specific elements to
be returned from it by using `params['_source']`.

Script fields can be accessed on the response using <<returned-fields,`.Fields`>>, similarly to stored fields.

See the Elasticsearch documentation on {ref_current}/search-request-body.html#request-body-search-script-fields[script fields]
for more detail.

[float]
=== Fluent DSL example

[source,csharp]
----
s => s
.ScriptFields(sf => sf
    .ScriptField("test1", sc => sc
        .Source("doc['numberOfCommits'].value * 2")
    )
    .ScriptField("test2", sc => sc
        .Source("doc['numberOfCommits'].value * params.factor")
        .Params(p => p
            .Add("factor", 2.0)
        )
    )
)
----

[float]
=== Object Initializer syntax example

[source,csharp]
----
new SearchRequest<Project>
{
    ScriptFields = new ScriptFields
    {
        { "test1", new ScriptField { Script = new InlineScript("doc['numberOfCommits'].value * 2") } },
        {
            "test2", new InlineScript("doc['numberOfCommits'].value * params.factor")
            {
                Params = new FluentDictionary<string, object>
                {
                    { "factor", 2.0 }
                }
            }
        }
    }
}
----

[source,javascript]
.Example json output
----
{
  "script_fields": {
    "test1": {
      "script": {
        "source": "doc['numberOfCommits'].value * 2"
      }
    },
    "test2": {
      "script": {
        "source": "doc['numberOfCommits'].value * params.factor",
        "params": {
          "factor": 2.0
        }
      }
    }
  }
}
----

