:ref_current: https://www.elastic.co/guide/en/elasticsearch/reference/7.10

:github: https://github.com/elastic/elasticsearch-net

:nuget: https://www.nuget.org/packages

////
IMPORTANT NOTE
==============
This file has been generated from https://github.com/elastic/elasticsearch-net/tree/7.x/src/Tests/Tests/Search/Request/SourceFilteringUsageTests.cs. 
If you wish to submit a PR for any spelling mistakes, typos or grammatical errors for this file,
please modify the original csharp file found at the link and submit the PR with that change. Thanks!
////

[[source-filtering-usage]]
== Source Filtering Usage

Allows to control how the `_source` field is returned with every hit.
By default operations return the contents of the `_source` field unless
you have used the fields parameter or if the `_source` field is disabled.

See the Elasticsearch documentation on {ref_current}/search-request-body.html#request-body-search-source-filtering[Source Filtering] for more detail.

[float]
=== Fluent DSL example

[source,csharp]
----
s => s
.Query(q => ProjectFilter)
.Source(src => src
    .IncludeAll()
    .Excludes(e => e
        .Fields(
            p => p.Description
        )
    )
)
----

[float]
=== Object Initializer syntax example

[source,csharp]
----
new SearchRequest<Project>
{
    Query = ProjectFilter,
    Source = new SourceFilter
    {
        Includes = "*",
        Excludes = Fields<Project>(p => p.Description)
    }
}
----

[source,javascript]
.Example json output
----
{
  "query": {
    "term": {
      "type": {
        "value": "project"
      }
    }
  },
  "_source": {
    "includes": [
      "*"
    ],
    "excludes": [
      "description"
    ]
  }
}
----

[float]
=== Handling Responses

[source,csharp]
----
response.ShouldBeValid();

foreach (var document in response.Documents)
{
    document.Name.Should().NotBeNull();
    document.StartedOn.Should().NotBe(default(DateTime));
    document.Description.Should().BeNull();
}
----

[float]
=== Fluent DSL example

[source,csharp]
----
s => s.Source(false)
----

[float]
=== Object Initializer syntax example

[source,csharp]
----
new SearchRequest<Project>
{
    Source = false
}
----

[source,javascript]
.Example json output
----
{
  "_source": false
}
----

[float]
=== Handling Responses

[source,csharp]
----
response.ShouldBeValid();
foreach (var hit in response.Hits)
    hit.Source.Should().BeNull();
----

