// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.
//
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// ------------------------------------------------
//
// This file is automatically generated.
// Please do not edit these files manually.
// Run the following in the root of the repository:
//
// ------------------------------------------------

using System.Threading;
using System.Threading.Tasks;

#nullable restore
namespace Nest
{
	public class IndicesNamespace : NamespacedClientProxy
	{
		internal IndicesNamespace(ElasticClient client) : base(client)
		{
		}

		public DeleteIndexResponse DeleteIndex(IDeleteIndexRequest request)
		{
			return DoRequest<IDeleteIndexRequest, DeleteIndexResponse>(request, request.RequestParameters);
		}

		public Task<DeleteIndexResponse> DeleteIndexAsync(IDeleteIndexRequest request, CancellationToken cancellationToken = default)
		{
			return DoRequestAsync<IDeleteIndexRequest, DeleteIndexResponse>(request, request.RequestParameters, cancellationToken);
		}

		public IndexTemplateExistsResponse IndexTemplateExists(IIndexTemplateExistsRequest request)
		{
			return DoRequest<IIndexTemplateExistsRequest, IndexTemplateExistsResponse>(request, request.RequestParameters);
		}

		public Task<IndexTemplateExistsResponse> IndexTemplateExistsAsync(IIndexTemplateExistsRequest request, CancellationToken cancellationToken = default)
		{
			return DoRequestAsync<IIndexTemplateExistsRequest, IndexTemplateExistsResponse>(request, request.RequestParameters, cancellationToken);
		}
	}
}