// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.
//
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// ------------------------------------------------
//
// This file is automatically generated.
// Please do not edit these files manually.
//
// ------------------------------------------------

#nullable restore

using System;
using System.Linq;
using Elastic.Clients.Elasticsearch.Serialization;

namespace Elastic.Clients.Elasticsearch;

public partial class ScriptSort : RequestConverter.ICodeFormattable
{
	public void FormatCode(RequestConverter.CodeWriter writer)
	{
		if (writer.EffectiveSyntaxMode == RequestConverter.SyntaxMode.Descriptor)
		{
			if (Mode is not null)
			{
				writer.WriteFluentCall("Mode", (w) => { Elastic.Clients.Elasticsearch.SortModeCodeFormatter.FormatCode(Mode.Value, w); });
			}

			if (Nested is not null)
			{
				writer.WriteFluentDescriptorCall("Nested", (w) => { Nested.FormatCode(w); }, (w) => { Nested.FormatCode(w); });
			}

			if (Order is not null)
			{
				writer.WriteFluentCall("Order", (w) => { Elastic.Clients.Elasticsearch.SortOrderCodeFormatter.FormatCode(Order.Value, w); });
			}

			{
				writer.WriteFluentDescriptorCall("Script", (w) => { Script.FormatCode(w); });
			}

			if (Type is not null)
			{
				writer.WriteFluentCall("Type", (w) => { Elastic.Clients.Elasticsearch.ScriptSortTypeCodeFormatter.FormatCode(Type.Value, w); });
			}
		}
		else
		{
			var initializer = writer.BeginObjectInitializer("Elastic.Clients.Elasticsearch.ScriptSort", false);
			if (Mode is not null)
			{
				initializer.Property("Mode");
				Elastic.Clients.Elasticsearch.SortModeCodeFormatter.FormatCode(Mode.Value, writer);
			}

			if (Nested is not null)
			{
				initializer.Property("Nested");
				Nested.FormatCode(writer);
			}

			if (Order is not null)
			{
				initializer.Property("Order");
				Elastic.Clients.Elasticsearch.SortOrderCodeFormatter.FormatCode(Order.Value, writer);
			}

			{
				initializer.Property("Script");
				Script.FormatCode(writer);
			}

			if (Type is not null)
			{
				initializer.Property("Type");
				Elastic.Clients.Elasticsearch.ScriptSortTypeCodeFormatter.FormatCode(Type.Value, writer);
			}

			initializer.Dispose();
		}
	}
}