// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.
//
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// ------------------------------------------------
//
// This file is automatically generated.
// Please do not edit these files manually.
//
// ------------------------------------------------

#nullable restore

using System;
using System.Linq;
using Elastic.Clients.Elasticsearch.Serialization;

namespace Elastic.Clients.Elasticsearch.Snapshot;

public partial class SharedFileSystemRepositorySettings : RequestConverter.ICodeFormattable
{
	public void FormatCode(RequestConverter.CodeWriter writer)
	{
		if (writer.EffectiveSyntaxMode == RequestConverter.SyntaxMode.Descriptor)
		{
			if (ChunkSize is not null)
			{
				writer.WriteFluentCall("ChunkSize", (w) => { ChunkSize.FormatCode(w); });
			}

			if (Compress is not null)
			{
				writer.WriteFluentCall("Compress", (w) => { w.WriteValue(Compress.Value); });
			}

			{
				writer.WriteFluentCall("Location", (w) => { w.WriteString(Location); });
			}

			if (MaxNumberOfSnapshots is not null)
			{
				writer.WriteFluentCall("MaxNumberOfSnapshots", (w) => { w.WriteValue(MaxNumberOfSnapshots.Value); });
			}

			if (MaxRestoreBytesPerSec is not null)
			{
				writer.WriteFluentCall("MaxRestoreBytesPerSec", (w) => { MaxRestoreBytesPerSec.FormatCode(w); });
			}

			if (MaxSnapshotBytesPerSec is not null)
			{
				writer.WriteFluentCall("MaxSnapshotBytesPerSec", (w) => { MaxSnapshotBytesPerSec.FormatCode(w); });
			}

			if (Readonly is not null)
			{
				writer.WriteFluentCall("Readonly", (w) => { w.WriteValue(Readonly.Value); });
			}
		}
		else
		{
			var initializer = writer.BeginObjectInitializer("Elastic.Clients.Elasticsearch.Snapshot.SharedFileSystemRepositorySettings", false);
			if (ChunkSize is not null)
			{
				initializer.Property("ChunkSize");
				ChunkSize.FormatCode(writer);
			}

			if (Compress is not null)
			{
				initializer.Property("Compress");
				writer.WriteValue(Compress.Value);
			}

			{
				initializer.Property("Location");
				writer.WriteString(Location);
			}

			if (MaxNumberOfSnapshots is not null)
			{
				initializer.Property("MaxNumberOfSnapshots");
				writer.WriteValue(MaxNumberOfSnapshots.Value);
			}

			if (MaxRestoreBytesPerSec is not null)
			{
				initializer.Property("MaxRestoreBytesPerSec");
				MaxRestoreBytesPerSec.FormatCode(writer);
			}

			if (MaxSnapshotBytesPerSec is not null)
			{
				initializer.Property("MaxSnapshotBytesPerSec");
				MaxSnapshotBytesPerSec.FormatCode(writer);
			}

			if (Readonly is not null)
			{
				initializer.Property("Readonly");
				writer.WriteValue(Readonly.Value);
			}

			initializer.Dispose();
		}
	}
}