:ref_current: https://www.elastic.co/guide/en/elasticsearch/reference/7.0

:github: https://github.com/elastic/elasticsearch-net

:nuget: https://www.nuget.org/packages

////
IMPORTANT NOTE
==============
This file has been generated from https://github.com/elastic/elasticsearch-net/tree/master/src/Tests/Tests/QueryDsl/Geo/Shape/GeoShapeQueryUsageTests.cs. 
If you wish to submit a PR for any spelling mistakes, typos or grammatical errors for this file,
please modify the original csharp file found at the link and submit the PR with that change. Thanks!
////

[[geo-shape-query-usage]]
=== Geo Shape Query Usage

The GeoShape Query uses the same grid square representation as the geo_shape mapping
to find documents that have a shape that intersects with the query shape.
It will also use the same PrefixTree configuration as defined for the field mapping.

The query supports two ways of defining the query shape, either by providing a whole
shape definition, or by referencing the name of a shape pre-indexed in another index.

See the Elasticsearch documentation on {ref_current}/query-dsl-geo-shape-query.html[geoshape queries] for more detail.

[[geo-shape-query-point]]
[float]
== Querying with Point

==== Fluent DSL example

[source,csharp]
----
q
.GeoShape(c => c
    .Name("named_query")
    .Boost(1.1)
    .Field(p => p.Location)
    .Shape(s => s
        .Point(PointCoordinates)
    )
    .Relation(GeoShapeRelation.Intersects)
)
----

==== Object Initializer syntax example

[source,csharp]
----
new GeoShapeQuery
{
    Name = "named_query",
    Boost = 1.1,
    Field = Infer.Field<Project>(p => p.Location),
    Shape = new PointGeoShape(PointCoordinates),
    Relation = GeoShapeRelation.Intersects,
}
----

[[geo-shape-query-multipoint]]
[float]
== Querying with MultiPoint

==== Object Initializer syntax example

[source,csharp]
----
new GeoShapeQuery
{
    Name = "named_query",
    Boost = 1.1,
    Field = Infer.Field<Project>(p => p.Location),
    Shape = new MultiPointGeoShape(MultiPointCoordinates),
    Relation = GeoShapeRelation.Intersects,
}
----

==== Fluent DSL example

[source,csharp]
----
q
.GeoShape(c => c
    .Name("named_query")
    .Boost(1.1)
    .Field(p => p.Location)
    .Shape(s => s
        .MultiPoint(MultiPointCoordinates)
    )
    .Relation(GeoShapeRelation.Intersects)
)
----

[[geo-shape-query-linestring]]
[float]
== Querying with LineString

==== Object Initializer syntax example

[source,csharp]
----
new GeoShapeQuery
{
    Name = "named_query",
    Boost = 1.1,
    Field = Infer.Field<Project>(p => p.Location),
    Shape = new LineStringGeoShape(LineStringCoordinates),
    Relation = GeoShapeRelation.Intersects,
}
----

==== Fluent DSL example

[source,csharp]
----
q
.GeoShape(c => c
    .Name("named_query")
    .Boost(1.1)
    .Field(p => p.Location)
    .Shape(s => s
        .LineString(LineStringCoordinates)
    )
    .Relation(GeoShapeRelation.Intersects)
)
----

[[geo-shape-query-multilinestring]]
[float]
== Querying with MultiLineString

==== Object Initializer syntax example

[source,csharp]
----
new GeoShapeQuery
{
    Name = "named_query",
    Boost = 1.1,
    Field = Infer.Field<Project>(p => p.Location),
    Shape = new MultiLineStringGeoShape(MultiLineStringCoordinates),
    Relation = GeoShapeRelation.Intersects,
}
----

==== Fluent DSL example

[source,csharp]
----
q
.GeoShape(c => c
    .Name("named_query")
    .Boost(1.1)
    .Field(p => p.Location)
    .Shape(s => s
        .MultiLineString(MultiLineStringCoordinates)
    )
    .Relation(GeoShapeRelation.Intersects)
)
----

[[geo-shape-query-polygon]]
[float]
== Querying with Polygon

==== Object Initializer syntax example

[source,csharp]
----
new GeoShapeQuery
{
    Name = "named_query",
    Boost = 1.1,
    Field = Infer.Field<Project>(p => p.Location),
    Shape = new PolygonGeoShape(PolygonCoordinates),
    IgnoreUnmapped = true,
    Relation = GeoShapeRelation.Intersects,
}
----

==== Fluent DSL example

[source,csharp]
----
q
.GeoShape(c => c
    .Name("named_query")
    .Boost(1.1)
    .Field(p => p.Location)
    .Shape(s => s
        .Polygon(PolygonCoordinates)
    )
    .IgnoreUnmapped()
    .Relation(GeoShapeRelation.Intersects)
)
----

[[geo-shape-query-multipolygon]]
[float]
== Querying with MultiPolygon

==== Object Initializer syntax example

[source,csharp]
----
new GeoShapeQuery
{
    Name = "named_query",
    Boost = 1.1,
    Field = Infer.Field<Project>(p => p.Location),
    Shape = new MultiPolygonGeoShape(MultiPolygonCoordinates),
    Relation = GeoShapeRelation.Intersects,
}
----

==== Fluent DSL example

[source,csharp]
----
q
.GeoShape(c => c
    .Name("named_query")
    .Boost(1.1)
    .Field(p => p.Location)
    .Shape(s => s
        .MultiPolygon(MultiPolygonCoordinates)
    )
    .Relation(GeoShapeRelation.Intersects)
)
----

[[geo-shape-query-geometrycollection]]
[float]
== Querying with GeometryCollection

==== Object Initializer syntax example

[source,csharp]
----
new GeoShapeQuery
{
    Name = "named_query",
    Boost = 1.1,
    Field = Infer.Field<Project>(p => p.Location),
    Shape = new GeometryCollection(new IGeoShape[]
    {
        new PointGeoShape(PointCoordinates),
        new MultiPointGeoShape(MultiPointCoordinates),
        new LineStringGeoShape(LineStringCoordinates),
        new MultiLineStringGeoShape(MultiLineStringCoordinates),
        new PolygonGeoShape(PolygonCoordinates),
        new MultiPolygonGeoShape(MultiPolygonCoordinates),
    }),
    Relation = GeoShapeRelation.Intersects,
}
----

==== Fluent DSL example

[source,csharp]
----
q
.GeoShape(c => c
    .Name("named_query")
    .Boost(1.1)
    .Field(p => p.Location)
    .Shape(s => s
        .GeometryCollection(
            new PointGeoShape(PointCoordinates),
            new MultiPointGeoShape(MultiPointCoordinates),
            new LineStringGeoShape(LineStringCoordinates),
            new MultiLineStringGeoShape(MultiLineStringCoordinates),
            new PolygonGeoShape(PolygonCoordinates),
            new MultiPolygonGeoShape(MultiPolygonCoordinates)
        )
    )
    .Relation(GeoShapeRelation.Intersects)
)
----

[[geo-shape-query-envelope]]
[float]
== Querying with Envelope

==== Object Initializer syntax example

[source,csharp]
----
new GeoShapeQuery
{
    Name = "named_query",
    Boost = 1.1,
    Field = Infer.Field<Project>(p => p.Location),
    Shape = new EnvelopeGeoShape(EnvelopeCoordinates),
    Relation = GeoShapeRelation.Intersects,
}
----

==== Fluent DSL example

[source,csharp]
----
q
.GeoShape(c => c
    .Name("named_query")
    .Boost(1.1)
    .Field(p => p.Location)
    .Shape(s => s
        .Envelope(EnvelopeCoordinates)
    )
    .Relation(GeoShapeRelation.Intersects)
)
----

[[geo-shape-query-circle]]
[float]
== Querying with Circle

==== Object Initializer syntax example

[source,csharp]
----
new GeoShapeQuery
{
    Name = "named_query",
    Boost = 1.1,
    Field = Infer.Field<Project>(p => p.Location),
    Shape = new CircleGeoShape(CircleCoordinates, "100m"),
    Relation = GeoShapeRelation.Intersects,
}
----

==== Fluent DSL example

[source,csharp]
----
q
.GeoShape(c => c
    .Name("named_query")
    .Boost(1.1)
    .Field(p => p.Location)
    .Shape(s => s
        .Circle(CircleCoordinates, "100m")
    )
    .Relation(GeoShapeRelation.Intersects)
)
----

[[geo-shape-query-indexedshape]]
[float]
== Querying with an indexed shape

The GeoShape Query supports using a shape which has already been indexed in another index and/or index type within a geoshape query.
This is particularly useful for when you have a pre-defined list of shapes which are useful to your application and you want to reference this
using a logical name (for example __New Zealand__), rather than having to provide their coordinates within the request each time.

See the Elasticsearch documentation on {ref_current}/query-dsl-geo-shape-query.html[geoshape queries] for more detail.

==== Object Initializer syntax example

[source,csharp]
----
new GeoShapeQuery
{
    Name = "named_query",
    Boost = 1.1,
    Field = Infer.Field<Project>(p => p.Location),
    IndexedShape = new FieldLookup
    {
        Id = 2,
        Index = Infer.Index<Project>(),
        Path = Infer.Field<Project>(p => p.Location),
    },
    Relation = GeoShapeRelation.Intersects
}
----

==== Fluent DSL example

[source,csharp]
----
q
.GeoShape(c => c
    .Name("named_query")
    .Boost(1.1)
    .Field(p => p.Location)
    .IndexedShape(p => p
        .Id(2)
        .Path(pp => pp.Location)
    )
    .Relation(GeoShapeRelation.Intersects)
)
----

