// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.
//
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// ------------------------------------------------
//
// This file is automatically generated.
// Please do not edit these files manually.
//
// ------------------------------------------------

#nullable restore

using System;
using System.Linq;
using Elastic.Clients.Elasticsearch.Serialization;

namespace Elastic.Clients.Elasticsearch.MachineLearning;

public partial class ValidateRequest : RequestConverter.ICodeFormattable
{
	public void FormatCode(RequestConverter.CodeWriter writer)
	{
		if (writer.EffectiveSyntaxMode == RequestConverter.SyntaxMode.Descriptor)
		{
			if (writer.Options.UseStronglyTypedDocument)
			{
				writer.Write("new ");
				writer.WriteTypeRef("Elastic.Clients.Elasticsearch.MachineLearning.ValidateRequestDescriptor<TDocument>");
				writer.Write("()");
			}
			else
			{
				writer.Write("new ");
				writer.WriteTypeRef("Elastic.Clients.Elasticsearch.MachineLearning.ValidateRequestDescriptor");
				writer.Write("()");
			}

			using var _chainIndent = writer.Indent();
			if (AnalysisConfig is not null)
			{
				writer.WriteFluentDescriptorCall("AnalysisConfig", (w) => { AnalysisConfig.FormatCode(w); });
			}

			if (AnalysisLimits is not null)
			{
				writer.WriteFluentDescriptorCall("AnalysisLimits", (w) => { AnalysisLimits.FormatCode(w); });
			}

			if (DataDescription is not null)
			{
				writer.WriteFluentDescriptorCall("DataDescription", (w) => { DataDescription.FormatCode(w); });
			}

			if (Description is not null)
			{
				writer.WriteFluentCall("Description", (w) => { using var _oi = w.ForceObjectInitializer(); w.WriteString(Description); });
			}

			if (JobId is not null)
			{
				writer.WriteFluentCall("JobId", (w) => { using var _oi = w.ForceObjectInitializer(); JobId.FormatCode(w); });
			}

			if (ModelPlot is not null)
			{
				writer.WriteFluentDescriptorCall("ModelPlot", (w) => { ModelPlot.FormatCode(w); });
			}

			if (ModelSnapshotId is not null)
			{
				writer.WriteFluentCall("ModelSnapshotId", (w) => { using var _oi = w.ForceObjectInitializer(); ModelSnapshotId.FormatCode(w); });
			}

			if (ModelSnapshotRetentionDays is not null)
			{
				writer.WriteFluentCall("ModelSnapshotRetentionDays", (w) => { using var _oi = w.ForceObjectInitializer(); w.WriteValue(ModelSnapshotRetentionDays.Value); w.Write("L"); });
			}

			if (ResultsIndexName is not null)
			{
				writer.WriteFluentCall("ResultsIndexName", (w) => { using var _oi = w.ForceObjectInitializer(); ResultsIndexName.FormatCode(w); });
			}
		}
		else
		{
			var initializer = writer.BeginObjectInitializer("Elastic.Clients.Elasticsearch.MachineLearning.ValidateRequest", false);
			if (AnalysisConfig is not null)
			{
				initializer.Property("AnalysisConfig");
				AnalysisConfig.FormatCode(writer);
			}

			if (AnalysisLimits is not null)
			{
				initializer.Property("AnalysisLimits");
				AnalysisLimits.FormatCode(writer);
			}

			if (DataDescription is not null)
			{
				initializer.Property("DataDescription");
				DataDescription.FormatCode(writer);
			}

			if (Description is not null)
			{
				initializer.Property("Description");
				writer.WriteString(Description);
			}

			if (JobId is not null)
			{
				initializer.Property("JobId");
				JobId.FormatCode(writer);
			}

			if (ModelPlot is not null)
			{
				initializer.Property("ModelPlot");
				ModelPlot.FormatCode(writer);
			}

			if (ModelSnapshotId is not null)
			{
				initializer.Property("ModelSnapshotId");
				ModelSnapshotId.FormatCode(writer);
			}

			if (ModelSnapshotRetentionDays is not null)
			{
				initializer.Property("ModelSnapshotRetentionDays");
				writer.WriteValue(ModelSnapshotRetentionDays.Value);
				writer.Write("L");
			}

			if (ResultsIndexName is not null)
			{
				initializer.Property("ResultsIndexName");
				ResultsIndexName.FormatCode(writer);
			}

			initializer.Dispose();
		}
	}
}