// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.
//
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// ------------------------------------------------
//
// This file is automatically generated.
// Please do not edit these files manually.
//
// ------------------------------------------------

#nullable restore

using System;
using System.Linq;
using Elastic.Clients.Elasticsearch.Serialization;

namespace Elastic.Clients.Elasticsearch.Aggregations;

[System.Text.Json.Serialization.JsonConverter(typeof(Elastic.Clients.Elasticsearch.Aggregations.Json.CardinalityExecutionModeConverter))]
public enum CardinalityExecutionMode
{
	/// <include file="CardinalityExecutionMode.g.xml" path="doc/member[@key='_types.aggregations.CardinalityExecutionMode#direct']/*"/>
	[System.Runtime.Serialization.EnumMember(Value = "direct")]
	Direct,
	/// <include file="CardinalityExecutionMode.g.xml" path="doc/member[@key='_types.aggregations.CardinalityExecutionMode#global_ordinals']/*"/>
	[System.Runtime.Serialization.EnumMember(Value = "global_ordinals")]
	GlobalOrdinals,
	/// <include file="CardinalityExecutionMode.g.xml" path="doc/member[@key='_types.aggregations.CardinalityExecutionMode#save_memory_heuristic']/*"/>
	[System.Runtime.Serialization.EnumMember(Value = "save_memory_heuristic")]
	SaveMemoryHeuristic,
	/// <include file="CardinalityExecutionMode.g.xml" path="doc/member[@key='_types.aggregations.CardinalityExecutionMode#save_time_heuristic']/*"/>
	[System.Runtime.Serialization.EnumMember(Value = "save_time_heuristic")]
	SaveTimeHeuristic,
	/// <include file="CardinalityExecutionMode.g.xml" path="doc/member[@key='_types.aggregations.CardinalityExecutionMode#segment_ordinals']/*"/>
	[System.Runtime.Serialization.EnumMember(Value = "segment_ordinals")]
	SegmentOrdinals
}