[[elasticsearch-net-breaking-changes]]
== Elasticsearch.Net Breaking Changes

This lists all the *binary* breaking changes in Elasticsearch.Net from 2.x to 5.x.

[float]
[[enums]]
=== Enums

*public enum Elasticsearch.Net.Consistency* _Removed (Breaking)_

*public enum Elasticsearch.Net.Bytes* _Declaration changed (Breaking)_

2.x

[source,csharp]
----
public enum Bytes
{
     B = 0,
     K = 1,
     M = 2,
     G = 3
}
----

5.x

[source,csharp]
----
public enum Bytes
{
     B = 0,
     K = 1,
     Kb = 2,
     M = 3,
     Mb = 4,
     G = 5,
     Gb = 6,
     T = 7,
     Tb = 8,
     P = 9,
     Pb = 10
}
----

*public enum Elasticsearch.Net.Feature* _Declaration changed (Breaking)_

2.x

[source,csharp]
----
[FlagsAttribute]
public enum Feature
{
     Settings = 1,
     Mappings = 2,
     Warmers = 4,
     Aliases = 8
}
----

5.x

[source,csharp]
----
[FlagsAttribute]
public enum Feature
{
     Settings = 1,
     Mappings = 2,
     Aliases = 4
}
----

*public enum Elasticsearch.Net.NodesStatsMetric* _Declaration changed
(Breaking)_

2.x

[source,csharp]
----
[FlagsAttribute]
public enum NodesStatsMetric
{
     Breaker = 1,
     Fs = 2,
     Http = 4,
     Indices = 8,
     Jvm = 16,
     Os = 32,
     Process = 64,
     ThreadPool = 128,
     Transport = 256,
     All = 512
}
----

5.x

[source,csharp]
----
[FlagsAttribute]
public enum NodesStatsMetric
{
     Breaker = 1,
     Fs = 2,
     Http = 4,
     Indices = 8,
     Jvm = 16,
     Os = 32,
     Process = 64,
     ThreadPool = 128,
     Transport = 256,
     Discovery = 512,
     All = 1024
}
----

*public enum Elasticsearch.Net.SearchType* _Declaration changed
(Breaking)_

2.x

[source,csharp]
----
public enum SearchType
{
     QueryThenFetch = 0,
     QueryAndFetch = 1,
     DfsQueryThenFetch = 2,
     DfsQueryAndFetch = 3,
     Count = 4,
     Scan = 5
}
----

5.x

[source,csharp]
----
public enum SearchType
{
     QueryThenFetch = 0,
     DfsQueryThenFetch = 1
}
----

[float]
[[refresh-no-longer-just-a-bool]]
=== Refresh no longer just a bool

Now an enum that can also send `wait_for`

*public method Elasticsearch.Net.BulkRequestParameters.Refresh*
_Declaration changed (Breaking)_

2.x: `public BulkRequestParameters Refresh(bool refresh)` +
5.x: `public BulkRequestParameters Refresh(Refresh refresh)`

*public method Elasticsearch.Net.DeleteRequestParameters.Refresh*
_Declaration changed (Breaking)_ +
*public method Elasticsearch.Net.IndexRequestParameters.Refresh*
_Declaration changed (Breaking)_ +
*public method Elasticsearch.Net.UpdateRequestParameters.Refresh*
_Declaration changed (Breaking)_


[float]
[[waitforactiveshards-now-takes-a-string]]
=== WaitForActiveShards now takes a string

So you can send `all`

*public method
Elasticsearch.Net.ClusterHealthRequestParameters.WaitForActiveShards*
_Declaration changed (Breaking)_

2.x:
`public ClusterHealthRequestParameters WaitForActiveShards(long wait_for_active_shards)` +
5.x:
`public ClusterHealthRequestParameters WaitForActiveShards(string wait_for_active_shards)`

[float]
[[elasticsearch-net-visibility-changes]]
=== Visibility changes

These were types/methods/properties/constructors that were public but
had no business being so.

*public method Elasticsearch.Net.RequestData..ctor* _Visibility was
changed from public to private (Breaking)_

2.x

[source,csharp]
----
[ObsoleteAttribute("This constructor is scheduled to become private in 5.0.0")]
public  .ctor(HttpMethod method, string path, PostData<object> data, IConnectionConfigurationValues global, IRequestConfiguration local, IMemoryStreamFactory memoryStreamFactory)
----

5.x

[source,csharp]
----
private  .ctor(HttpMethod method, string path, PostData<object> data, IConnectionConfigurationValues global, IRequestConfiguration local, IMemoryStreamFactory memoryStreamFactory)
----

*public property
Elasticsearch.Net.Transport<TConnectionSettings>.DateTimeProvider*
_Visibility was changed from public to private (Breaking)_

2.x: `public IDateTimeProvider DateTimeProvider { get; }` +
5.x: `private IDateTimeProvider DateTimeProvider { get; }`

*public property
Elasticsearch.Net.Transport<TConnectionSettings>.MemoryStreamFactory*
_Visibility was changed from public to private (Breaking)_

2.x: `public IMemoryStreamFactory MemoryStreamFactory { get; }` +
5.x: `private IMemoryStreamFactory MemoryStreamFactory { get; }`

*public property
Elasticsearch.Net.Transport<TConnectionSettings>.PipelineProvider*
_Visibility was changed from public to private (Breaking)_

2.x: `public IRequestPipelineFactory PipelineProvider { get; }` +
5.x: `private IRequestPipelineFactory PipelineProvider { get; }`

[float]
[[rename-of-api-related-methods]]
=== Rename of API related methods

Impact low, these have been renamed to match their Method name
equivalents

*public method Elasticsearch.Net.ElasticLowLevelClient.CatNodeattrs<T>*
_Declaration changed (Breaking)_

2.x:
`public ElasticsearchResponse<T> CatNodeattrs<T>(Func<CatNodeattrsRequestParameters, CatNodeattrsRequestParameters> requestParameters)` +
5.x:
`public ElasticsearchResponse<T> CatNodeattrs<T>(Func<CatNodeAttributesRequestParameters, CatNodeAttributesRequestParameters> requestParameters)`

*public method Elasticsearch.Net.ElasticLowLevelClient.TasksCancel<T>*
_Declaration changed (Breaking)_

2.x:
`public ElasticsearchResponse<T> TasksCancel<T>(string task_id, Func<TasksCancelRequestParameters, TasksCancelRequestParameters> requestParameters)` +
5.x:
`public ElasticsearchResponse<T> TasksCancel<T>(string task_id, Func<CancelTasksRequestParameters, CancelTasksRequestParameters> requestParameters)`

*public method Elasticsearch.Net.ElasticLowLevelClient.TasksCancel<T>*
_Declaration changed (Breaking)_

2.x:
`public ElasticsearchResponse<T> TasksCancel<T>(Func<TasksCancelRequestParameters, TasksCancelRequestParameters> requestParameters)` +
5.x:
`public ElasticsearchResponse<T> TasksCancel<T>(Func<CancelTasksRequestParameters, CancelTasksRequestParameters> requestParameters)`

*public method Elasticsearch.Net.ElasticLowLevelClient.TasksList<T>*
_Declaration changed (Breaking)_

2.x:
`public ElasticsearchResponse<T> TasksList<T>(Func<TasksListRequestParameters, TasksListRequestParameters> requestParameters)` +
5.x:
`public ElasticsearchResponse<T> TasksList<T>(Func<ListTasksRequestParameters, ListTasksRequestParameters> requestParameters)`

*public method Elasticsearch.Net.IElasticLowLevelClient.CatNodeattrs<T>*
_Declaration changed (Breaking)_

2.x:
`public ElasticsearchResponse<T> CatNodeattrs<T>(Func<CatNodeattrsRequestParameters, CatNodeattrsRequestParameters> requestParameters)` +
5.x:
`public ElasticsearchResponse<T> CatNodeattrs<T>(Func<CatNodeAttributesRequestParameters, CatNodeAttributesRequestParameters> requestParameters)`

*public method Elasticsearch.Net.IElasticLowLevelClient.TasksCancel<T>*
_Declaration changed (Breaking)_

2.x:
`public ElasticsearchResponse<T> TasksCancel<T>(string task_id, Func<TasksCancelRequestParameters, TasksCancelRequestParameters> requestParameters)` +
5.x:
`public ElasticsearchResponse<T> TasksCancel<T>(string task_id, Func<CancelTasksRequestParameters, CancelTasksRequestParameters> requestParameters)`

*public method Elasticsearch.Net.IElasticLowLevelClient.TasksCancel<T>*
_Declaration changed (Breaking)_

2.x:
`public ElasticsearchResponse<T> TasksCancel<T>(Func<TasksCancelRequestParameters, TasksCancelRequestParameters> requestParameters)` +
5.x:
`public ElasticsearchResponse<T> TasksCancel<T>(Func<CancelTasksRequestParameters, CancelTasksRequestParameters> requestParameters)`

*public method Elasticsearch.Net.IElasticLowLevelClient.TasksList<T>*
_Declaration changed (Breaking)_

2.x:
`public ElasticsearchResponse<T> TasksList<T>(Func<TasksListRequestParameters, TasksListRequestParameters> requestParameters)` +
5.x:
`public ElasticsearchResponse<T> TasksList<T>(Func<ListTasksRequestParameters, ListTasksRequestParameters> requestParameters)`

[float]
[[rest-spec-updates]]
=== Rest spec updates

These are breaking changes due to the Elasticsearch 5.0 rest spec
changing

*public method Elasticsearch.Net.DeleteByQueryRequestParameters.Routing*
_Declaration changed (Breaking)_

2.x: `public DeleteByQueryRequestParameters Routing(string routing)` +
5.x: `public DeleteByQueryRequestParameters Routing(String[] routing)`

*public method
Elasticsearch.Net.ReindexOnServerRequestParameters.RequestsPerSecond*
_Declaration changed (Breaking)_

2.x:
`public ReindexOnServerRequestParameters RequestsPerSecond(Single requests_per_second)` +
5.x:
`public ReindexOnServerRequestParameters RequestsPerSecond(long requests_per_second)`

*public method
Elasticsearch.Net.ReindexRethrottleRequestParameters.RequestsPerSecond*
_Declaration changed (Breaking)_

2.x:
`public ReindexRethrottleRequestParameters RequestsPerSecond(Single requests_per_second)` +
5.x:
`public ReindexRethrottleRequestParameters RequestsPerSecond(long requests_per_second)`

*public method
Elasticsearch.Net.UpdateByQueryRequestParameters.RequestsPerSecond*
_Declaration changed (Breaking)_

2.x:
`public UpdateByQueryRequestParameters RequestsPerSecond(Single requests_per_second)` +
5.x:
`public UpdateByQueryRequestParameters RequestsPerSecond(long requests_per_second)`

[float]
[[removed-in-5.x-after-obsolete-period]]
=== Removed in 5.x after obsolete period

These are types/properties/methods marked obsolete in Elasticsearch.Net 2.x that have
now been removed.

*public method Elasticsearch.Net.AnalyzeRequestParameters.Analyzer*
_Removed (Breaking)_

[source,csharp]
----
[ObsoleteAttribute("Deprecated. Specify the analyzer to use in the body of the request.")]
public AnalyzeRequestParameters Analyzer(string analyzer)
----

*public method Elasticsearch.Net.AnalyzeRequestParameters.CharFilter*
_Removed (Breaking)_

[source,csharp]
----
[ObsoleteAttribute("Deprecated. Specify the char filters to use in the body of the request.")]
public AnalyzeRequestParameters CharFilter(String[] char_filter)
----

*public method Elasticsearch.Net.AnalyzeRequestParameters.CharFilters*
_Removed (Breaking)_

[source,csharp]
----
[ObsoleteAttribute("Deprecated. Specify the char filters to use in the body of the request.")]
public AnalyzeRequestParameters CharFilters(String[] char_filters)
----

*public method Elasticsearch.Net.AnalyzeRequestParameters.Field*
_Removed (Breaking)_

[source,csharp]
----
[ObsoleteAttribute("Deprecated. Specify the field to use in the body of the request.")]
public AnalyzeRequestParameters Field(string field)
----

*public method Elasticsearch.Net.AnalyzeRequestParameters.Filter*
_Removed (Breaking)_

[source,csharp]
----
[ObsoleteAttribute("Deprecated. Specify the filters to use in the body of the request.")]
public AnalyzeRequestParameters Filter(String[] filter)
----

*public method Elasticsearch.Net.AnalyzeRequestParameters.Filters*
_Removed (Breaking)_

[source,csharp]
----
[ObsoleteAttribute("Deprecated. Specify the filters to use in the body of the request.")]
public AnalyzeRequestParameters Filters(String[] filters)
----

*public method Elasticsearch.Net.AnalyzeRequestParameters.Text* _Removed
(Breaking)_

[source,csharp]
----
[ObsoleteAttribute("Deprecated. Specify the text to use in the body of the request.")]
public AnalyzeRequestParameters Text(String[] text)
----

*public method Elasticsearch.Net.AnalyzeRequestParameters.Tokenizer*
_Removed (Breaking)_

[source,csharp]
----
[ObsoleteAttribute("Deprecated. Specify the tokenizer to use in the body of the request.")]
public AnalyzeRequestParameters Tokenizer(string tokenizer)
----

*public property
Elasticsearch.Net.BasicAuthenticationCredentials.UserName* _Removed
(Breaking)_

[source,csharp]
----
[ObsoleteAttribute("Removed in 5.0.0. Use Username instead, note the lowercase n")]
[CLSCompliantAttribute(False)]
public string UserName { get; set; }
----

*public method Elasticsearch.Net.RequestData..ctor* _Removed (Breaking)_

[source,csharp]
----
[ObsoleteAttribute("Removed in 5.0.0")]
public  .ctor(HttpMethod method, string path, PostData<object> data, IConnectionConfigurationValues global, IMemoryStreamFactory memoryStreamFactory)
----

[float]
[[elasticsearch-net-now-ireadonlycollection]]
=== Now IReadOnlyCollection

*public property Elasticsearch.Net.Error.RootCause*

[float]
[[elasticsearch-net-cancellationtoken]]
=== CancellationToken

Async methods now expose CancellationToken directly in the method
signature, you no longer have to set this on `RequestConfiguration`

*Elasticsearch.Net.ElasticLowLevelClient.BulkAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.BulkAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.BulkAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.BulkPutAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.BulkPutAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.BulkPutAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CatAliasesAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CatAliasesAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CatAllocationAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CatAllocationAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CatCountAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CatCountAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CatFielddataAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CatFielddataAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CatHealthAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CatHelpAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CatIndicesAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CatIndicesAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CatMasterAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CatNodeattrsAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CatNodesAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CatPendingTasksAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CatPluginsAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CatRecoveryAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CatRecoveryAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CatRepositoriesAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CatSegmentsAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CatSegmentsAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CatShardsAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CatShardsAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CatSnapshotsAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CatThreadPoolAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.ClearScrollAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.ClusterGetSettingsAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.ClusterHealthAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.ClusterHealthAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.ClusterPendingTasksAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.ClusterPutSettingsAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.ClusterRerouteAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.ClusterStateAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.ClusterStateAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.ClusterStateAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.ClusterStatsAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.ClusterStatsAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CountAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CountAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CountAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CountGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CountGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CountGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CountPercolateAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CountPercolateAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CountPercolateGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.CountPercolateGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.DeleteAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.DeleteByQueryAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.DeleteByQueryAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.DeleteScriptAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.DeleteTemplateAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.DoRequestAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.ExistsAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.ExplainAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.ExplainGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.FieldStatsAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.FieldStatsAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.FieldStatsGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.FieldStatsGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.GetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.GetScriptAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.GetSourceAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.GetTemplateAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndexAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndexAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndexPutAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndexPutAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesAnalyzeAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesAnalyzeForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesAnalyzeGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesAnalyzeGetForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesClearCacheAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesClearCacheForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesClearCacheGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesClearCacheGetForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesCloseAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesCreateAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesDeleteAliasAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesDeleteAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesDeleteTemplateForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesExistsAliasAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesExistsAliasAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesExistsAliasForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesExistsAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesExistsTemplateForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesExistsTypeAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesFlushAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesFlushForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesFlushGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesFlushGetForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesFlushSyncedAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesFlushSyncedForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesFlushSyncedGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesFlushSyncedGetForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesForcemergeAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesForcemergeForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesGetAliasAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesGetAliasAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesGetAliasForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesGetAliasForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesGetFieldMappingAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesGetFieldMappingAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesGetFieldMappingForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesGetFieldMappingForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesGetMappingAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesGetMappingAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesGetMappingForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesGetMappingForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesGetSettingsAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesGetSettingsAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesGetSettingsForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesGetSettingsForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesGetTemplateForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesGetTemplateForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesGetUpgradeAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesGetUpgradeForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesOpenAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesPutAliasAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesPutAliasPostAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesPutMappingAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesPutMappingForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesPutMappingPostAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesPutMappingPostForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesPutSettingsAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesPutSettingsForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesPutTemplateForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesPutTemplatePostForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesRecoveryAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesRecoveryForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesRefreshAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesRefreshForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesRefreshGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesRefreshGetForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesSegmentsAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesSegmentsForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesShardStoresAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesShardStoresForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesStatsAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesStatsAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesStatsForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesStatsForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesUpdateAliasesForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesUpgradeAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesUpgradeForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesValidateQueryAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesValidateQueryAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesValidateQueryForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesValidateQueryGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesValidateQueryGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.IndicesValidateQueryGetForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.InfoAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.MgetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.MgetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.MgetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.MgetGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.MgetGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.MgetGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.MpercolateAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.MpercolateAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.MpercolateAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.MpercolateGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.MpercolateGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.MpercolateGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.MsearchAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.MsearchAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.MsearchAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.MsearchGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.MsearchGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.MsearchGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.MtermvectorsAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.MtermvectorsAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.MtermvectorsAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.MtermvectorsGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.MtermvectorsGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.MtermvectorsGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.NodesHotThreadsAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.NodesHotThreadsForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.NodesInfoAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.NodesInfoAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.NodesInfoForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.NodesInfoForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.NodesStatsAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.NodesStatsAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.NodesStatsAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.NodesStatsForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.NodesStatsForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.NodesStatsForAllAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.PercolateAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.PercolateAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.PercolateGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.PercolateGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.PingAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.PutScriptAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.PutScriptPostAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.PutTemplateAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.PutTemplatePostAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.ReindexAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.ReindexRethrottleAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.RenderSearchTemplateAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.RenderSearchTemplateAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.RenderSearchTemplateGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.RenderSearchTemplateGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.ScrollAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.ScrollGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SearchAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SearchAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SearchAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SearchGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SearchGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SearchGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SearchShardsAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SearchShardsAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SearchShardsAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SearchShardsGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SearchShardsGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SearchShardsGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SearchTemplateAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SearchTemplateAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SearchTemplateAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SearchTemplateGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SearchTemplateGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SearchTemplateGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SnapshotCreateAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SnapshotCreatePostAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SnapshotCreateRepositoryAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SnapshotCreateRepositoryPostAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SnapshotDeleteAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SnapshotDeleteRepositoryAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SnapshotGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SnapshotGetRepositoryAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SnapshotGetRepositoryAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SnapshotRestoreAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SnapshotStatusAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SnapshotStatusAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SnapshotStatusAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SnapshotVerifyRepositoryAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SuggestAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SuggestAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SuggestGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.SuggestGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.TasksCancelAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.TasksCancelAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.TasksListAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.TermvectorsAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.TermvectorsAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.TermvectorsGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.TermvectorsGetAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.UpdateAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.UpdateByQueryAsync<T>* +
*Elasticsearch.Net.ElasticLowLevelClient.UpdateByQueryAsync<T>* +
*Elasticsearch.Net.HttpConnection.RequestAsync<TReturn>* +
*Elasticsearch.Net.IConnection.RequestAsync<TReturn>* +
*Elasticsearch.Net.IElasticLowLevelClient.BulkAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.BulkAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.BulkAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.BulkPutAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.BulkPutAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.BulkPutAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CatAliasesAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CatAliasesAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CatAllocationAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CatAllocationAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CatCountAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CatCountAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CatFielddataAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CatFielddataAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CatHealthAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CatHelpAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CatIndicesAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CatIndicesAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CatMasterAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CatNodeattrsAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CatNodesAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CatPendingTasksAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CatPluginsAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CatRecoveryAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CatRecoveryAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CatRepositoriesAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CatSegmentsAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CatSegmentsAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CatShardsAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CatShardsAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CatSnapshotsAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CatThreadPoolAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.ClearScrollAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.ClusterGetSettingsAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.ClusterHealthAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.ClusterHealthAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.ClusterPendingTasksAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.ClusterPutSettingsAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.ClusterRerouteAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.ClusterStateAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.ClusterStateAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.ClusterStateAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.ClusterStatsAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.ClusterStatsAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CountAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CountAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CountAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CountGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CountGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CountGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CountPercolateAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CountPercolateAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CountPercolateGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.CountPercolateGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.DeleteAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.DeleteByQueryAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.DeleteByQueryAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.DeleteScriptAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.DeleteTemplateAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.DoRequestAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.ExistsAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.ExplainAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.ExplainGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.FieldStatsAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.FieldStatsAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.FieldStatsGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.FieldStatsGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.GetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.GetScriptAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.GetSourceAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.GetTemplateAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndexAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndexAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndexPutAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndexPutAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesAnalyzeAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesAnalyzeForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesAnalyzeGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesAnalyzeGetForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesClearCacheAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesClearCacheForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesClearCacheGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesClearCacheGetForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesCloseAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesCreateAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesDeleteAliasAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesDeleteAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesDeleteTemplateForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesExistsAliasAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesExistsAliasAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesExistsAliasForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesExistsAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesExistsTemplateForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesExistsTypeAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesFlushAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesFlushForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesFlushGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesFlushGetForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesFlushSyncedAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesFlushSyncedForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesFlushSyncedGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesFlushSyncedGetForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesForcemergeAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesForcemergeForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesGetAliasAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesGetAliasAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesGetAliasForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesGetAliasForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesGetFieldMappingAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesGetFieldMappingAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesGetFieldMappingForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesGetFieldMappingForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesGetMappingAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesGetMappingAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesGetMappingForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesGetMappingForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesGetSettingsAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesGetSettingsAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesGetSettingsForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesGetSettingsForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesGetTemplateForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesGetTemplateForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesGetUpgradeAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesGetUpgradeForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesOpenAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesPutAliasAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesPutAliasPostAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesPutMappingAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesPutMappingForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesPutMappingPostAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesPutMappingPostForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesPutSettingsAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesPutSettingsForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesPutTemplateForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesPutTemplatePostForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesRecoveryAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesRecoveryForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesRefreshAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesRefreshForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesRefreshGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesRefreshGetForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesSegmentsAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesSegmentsForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesShardStoresAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesShardStoresForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesStatsAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesStatsAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesStatsForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesStatsForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesUpdateAliasesForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesUpgradeAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesUpgradeForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesValidateQueryAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesValidateQueryAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesValidateQueryForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesValidateQueryGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesValidateQueryGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.IndicesValidateQueryGetForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.InfoAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.MgetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.MgetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.MgetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.MgetGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.MgetGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.MgetGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.MpercolateAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.MpercolateAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.MpercolateAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.MpercolateGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.MpercolateGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.MpercolateGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.MsearchAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.MsearchAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.MsearchAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.MsearchGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.MsearchGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.MsearchGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.MtermvectorsAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.MtermvectorsAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.MtermvectorsAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.MtermvectorsGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.MtermvectorsGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.MtermvectorsGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.NodesHotThreadsAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.NodesHotThreadsForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.NodesInfoAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.NodesInfoAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.NodesInfoForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.NodesInfoForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.NodesStatsAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.NodesStatsAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.NodesStatsAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.NodesStatsForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.NodesStatsForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.NodesStatsForAllAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.PercolateAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.PercolateAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.PercolateGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.PercolateGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.PingAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.PutScriptAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.PutScriptPostAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.PutTemplateAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.PutTemplatePostAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.ReindexAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.ReindexRethrottleAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.RenderSearchTemplateAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.RenderSearchTemplateAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.RenderSearchTemplateGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.RenderSearchTemplateGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.ScrollAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.ScrollGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SearchAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SearchAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SearchAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SearchGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SearchGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SearchGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SearchShardsAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SearchShardsAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SearchShardsAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SearchShardsGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SearchShardsGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SearchShardsGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SearchTemplateAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SearchTemplateAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SearchTemplateAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SearchTemplateGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SearchTemplateGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SearchTemplateGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SnapshotCreateAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SnapshotCreatePostAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SnapshotCreateRepositoryAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SnapshotCreateRepositoryPostAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SnapshotDeleteAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SnapshotDeleteRepositoryAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SnapshotGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SnapshotGetRepositoryAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SnapshotGetRepositoryAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SnapshotRestoreAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SnapshotStatusAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SnapshotStatusAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SnapshotStatusAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SnapshotVerifyRepositoryAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SuggestAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SuggestAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SuggestGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.SuggestGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.TasksCancelAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.TasksCancelAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.TasksListAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.TermvectorsAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.TermvectorsAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.TermvectorsGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.TermvectorsGetAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.UpdateAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.UpdateByQueryAsync<T>* +
*Elasticsearch.Net.IElasticLowLevelClient.UpdateByQueryAsync<T>* +
*Elasticsearch.Net.InMemoryConnection.RequestAsync<TReturn>* +
*Elasticsearch.Net.IRequestPipeline.CallElasticsearchAsync<TReturn>* +
*Elasticsearch.Net.IRequestPipeline.FirstPoolUsageAsync* +
*Elasticsearch.Net.IRequestPipeline.PingAsync* +
*Elasticsearch.Net.IRequestPipeline.SniffAsync* +
*Elasticsearch.Net.IRequestPipeline.SniffOnConnectionFailureAsync* +
*Elasticsearch.Net.IRequestPipeline.SniffOnStaleClusterAsync* +
*Elasticsearch.Net.ITransport<TConnectionSettings>.RequestAsync<T>* +
*Elasticsearch.Net.RequestPipeline.CallElasticsearchAsync<TReturn>* +
*Elasticsearch.Net.RequestPipeline.FirstPoolUsageAsync* +
*Elasticsearch.Net.RequestPipeline.PingAsync* +
*Elasticsearch.Net.RequestPipeline.SniffAsync* +
*Elasticsearch.Net.RequestPipeline.SniffOnConnectionFailureAsync* +
*Elasticsearch.Net.RequestPipeline.SniffOnStaleClusterAsync* +
*Elasticsearch.Net.ResponseBuilder<TReturn>..ctor* +
*Elasticsearch.Net.Transport<TConnectionSettings>.RequestAsync<TReturn>*

[float]
[[removed-in-elasticsearch-net-5.x]]
=== Removed in 5.x

These no longer exist in 5.x, either they have been renamed or are part
of previous mentioned changes

*public method Elasticsearch.Net.BulkRequestParameters.Consistency*
_Removed (Breaking)_ *public class
Elasticsearch.Net.CatNodeattrsRequestParameters* _Removed (Breaking)_
*public method Elasticsearch.Net.CatThreadPoolRequestParameters.FullId*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ClusterHealthRequestParameters.WaitForRelocatingShards*
_Removed (Breaking)_ *public method
Elasticsearch.Net.DeleteRequestParameters.Consistency* _Removed
(Breaking)_ *public method
Elasticsearch.Net.DeleteScriptRequestParameters.Version* _Removed
(Breaking)_ *public method
Elasticsearch.Net.DeleteScriptRequestParameters.VersionType* _Removed
(Breaking)_ *public method
Elasticsearch.Net.DeleteSearchTemplateRequestParameters.Version*
_Removed (Breaking)_ *public method
Elasticsearch.Net.DeleteSearchTemplateRequestParameters.VersionType*
_Removed (Breaking)_ *public class
Elasticsearch.Net.DeleteWarmerRequestParameters* _Removed (Breaking)_
*public method Elasticsearch.Net.DeleteWatchRequestParameters.Force*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.GraphExplore<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.GraphExplore<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.GraphExploreAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.GraphExploreAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.GraphExploreGet<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.GraphExploreGet<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.GraphExploreGetAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.GraphExploreGetAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesCreatePost<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesCreatePostAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesDeleteWarmer<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesDeleteWarmerAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesForcemergeGet<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesForcemergeGetAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesForcemergeGetForAll<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesForcemergeGetForAllAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesGetAliases<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesGetAliases<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesGetAliasesAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesGetAliasesAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesGetAliasesForAll<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesGetAliasesForAll<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesGetAliasesForAllAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesGetAliasesForAllAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesGetWarmer<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesGetWarmer<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesGetWarmer<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesGetWarmerAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesGetWarmerAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesGetWarmerAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesGetWarmerForAll<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesGetWarmerForAll<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesGetWarmerForAllAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesGetWarmerForAllAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesOptimize<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesOptimizeAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesOptimizeForAll<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesOptimizeForAllAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesOptimizeGet<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesOptimizeGetAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesOptimizeGetForAll<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesOptimizeGetForAllAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesPutWarmer<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesPutWarmer<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesPutWarmerAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesPutWarmerAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesPutWarmerForAll<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesPutWarmerForAllAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesPutWarmerPost<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesPutWarmerPost<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesPutWarmerPostAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesPutWarmerPostAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesPutWarmerPostForAll<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.IndicesPutWarmerPostForAllAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.LicenseDelete<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.LicenseDeleteAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.LicenseGet<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.LicenseGetAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.LicensePost<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.LicensePostAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.SearchExists<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.SearchExists<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.SearchExists<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.SearchExistsAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.SearchExistsAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.SearchExistsAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.SearchExistsGet<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.SearchExistsGet<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.SearchExistsGet<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.SearchExistsGetAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.SearchExistsGetAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.SearchExistsGetAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.ShieldAuthenticate<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.ShieldAuthenticateAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.ShieldClearCachedRealms<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.ShieldClearCachedRealmsAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.ShieldClearCachedRoles<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.ShieldClearCachedRolesAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.ShieldClearCachedRolesPut<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.ShieldClearCachedRolesPutAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.ShieldDeleteRole<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.ShieldDeleteRoleAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.ShieldDeleteUser<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.ShieldDeleteUserAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.ShieldGetRole<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.ShieldGetRole<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.ShieldGetRoleAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.ShieldGetRoleAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.ShieldGetUser<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.ShieldGetUser<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.ShieldGetUserAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.ShieldGetUserAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.ShieldPutRole<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.ShieldPutRoleAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.ShieldPutRolePost<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.ShieldPutRolePostAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.ShieldPutUser<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.ShieldPutUserAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.ShieldPutUserPost<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.ShieldPutUserPostAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.TasksList<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.TasksListAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherAckWatch<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherAckWatch<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherAckWatchAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherAckWatchAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherAckWatchPost<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherAckWatchPost<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherAckWatchPostAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherAckWatchPostAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherActivateWatch<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherActivateWatchAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherActivateWatchPost<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherActivateWatchPostAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherDeactivateWatch<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherDeactivateWatchAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherDeactivateWatchPost<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherDeactivateWatchPostAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherDeleteWatch<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherDeleteWatchAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherExecuteWatch<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherExecuteWatch<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherExecuteWatchAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherExecuteWatchAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherExecuteWatchPost<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherExecuteWatchPost<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherExecuteWatchPostAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherExecuteWatchPostAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherGetWatch<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherGetWatchAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherInfo<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherInfoAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherPutWatch<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherPutWatchAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherPutWatchPost<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherPutWatchPostAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherRestart<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherRestartAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherStart<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherStartAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherStats<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherStats<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherStatsAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherStatsAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherStop<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ElasticLowLevelClient.WatcherStopAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.ExplainRequestParameters.Fields* _Removed (Breaking)_
*public class Elasticsearch.Net.GetAliasesRequestParameters* _Removed
(Breaking)_ *public method
Elasticsearch.Net.GetRequestParameters.Fields* _Removed (Breaking)_
*public method Elasticsearch.Net.GetScriptRequestParameters.Version*
_Removed (Breaking)_ *public method
Elasticsearch.Net.GetScriptRequestParameters.VersionType* _Removed
(Breaking)_ *public method
Elasticsearch.Net.GetSearchTemplateRequestParameters.Version* _Removed
(Breaking)_ *public method
Elasticsearch.Net.GetSearchTemplateRequestParameters.VersionType*
_Removed (Breaking)_ *public class
Elasticsearch.Net.GetWarmerRequestParameters* _Removed (Breaking)_
*public property Elasticsearch.Net.IBodyWithApiCallDetails.CallDetails*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.GraphExplore<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.GraphExplore<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.GraphExploreAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.GraphExploreAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.GraphExploreGet<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.GraphExploreGet<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.GraphExploreGetAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.GraphExploreGetAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesCreatePost<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesCreatePostAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesDeleteWarmer<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesDeleteWarmerAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesForcemergeGet<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesForcemergeGetAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesForcemergeGetForAll<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesForcemergeGetForAllAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesGetAliases<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesGetAliases<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesGetAliasesAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesGetAliasesAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesGetAliasesForAll<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesGetAliasesForAll<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesGetAliasesForAllAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesGetAliasesForAllAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesGetWarmer<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesGetWarmer<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesGetWarmer<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesGetWarmerAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesGetWarmerAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesGetWarmerAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesGetWarmerForAll<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesGetWarmerForAll<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesGetWarmerForAllAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesGetWarmerForAllAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesOptimize<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesOptimizeAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesOptimizeForAll<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesOptimizeForAllAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesOptimizeGet<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesOptimizeGetAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesOptimizeGetForAll<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesOptimizeGetForAllAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesPutWarmer<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesPutWarmer<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesPutWarmerAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesPutWarmerAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesPutWarmerForAll<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesPutWarmerForAllAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesPutWarmerPost<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesPutWarmerPost<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesPutWarmerPostAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesPutWarmerPostAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesPutWarmerPostForAll<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.IndicesPutWarmerPostForAllAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.LicenseDelete<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.LicenseDeleteAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.LicenseGet<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.LicenseGetAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.LicensePost<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.LicensePostAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.SearchExists<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.SearchExists<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.SearchExists<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.SearchExistsAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.SearchExistsAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.SearchExistsAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.SearchExistsGet<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.SearchExistsGet<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.SearchExistsGet<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.SearchExistsGetAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.SearchExistsGetAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.SearchExistsGetAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.ShieldAuthenticate<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.ShieldAuthenticateAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.ShieldClearCachedRealms<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.ShieldClearCachedRealmsAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.ShieldClearCachedRoles<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.ShieldClearCachedRolesAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.ShieldClearCachedRolesPut<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.ShieldClearCachedRolesPutAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.ShieldDeleteRole<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.ShieldDeleteRoleAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.ShieldDeleteUser<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.ShieldDeleteUserAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.ShieldGetRole<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.ShieldGetRole<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.ShieldGetRoleAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.ShieldGetRoleAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.ShieldGetUser<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.ShieldGetUser<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.ShieldGetUserAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.ShieldGetUserAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.ShieldPutRole<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.ShieldPutRoleAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.ShieldPutRolePost<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.ShieldPutRolePostAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.ShieldPutUser<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.ShieldPutUserAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.ShieldPutUserPost<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.ShieldPutUserPostAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.TasksList<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.TasksListAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherAckWatch<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherAckWatch<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherAckWatchAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherAckWatchAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherAckWatchPost<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherAckWatchPost<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherAckWatchPostAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherAckWatchPostAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherActivateWatch<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherActivateWatchAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherActivateWatchPost<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherActivateWatchPostAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherDeactivateWatch<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherDeactivateWatchAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherDeactivateWatchPost<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherDeactivateWatchPostAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherDeleteWatch<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherDeleteWatchAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherExecuteWatch<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherExecuteWatch<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherExecuteWatchAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherExecuteWatchAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherExecuteWatchPost<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherExecuteWatchPost<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherExecuteWatchPostAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherExecuteWatchPostAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherGetWatch<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherGetWatchAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherInfo<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherInfoAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherPutWatch<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherPutWatchAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherPutWatchPost<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherPutWatchPostAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherRestart<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherRestartAsync<T>*
_Removed (Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherStart<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherStartAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherStats<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherStats<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherStatsAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherStatsAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherStop<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IElasticLowLevelClient.WatcherStopAsync<T>* _Removed
(Breaking)_ *public method
Elasticsearch.Net.IndexRequestParameters.Consistency* _Removed
(Breaking)_ *public property
Elasticsearch.Net.IRequestConfiguration.CancellationToken* _Removed
(Breaking)_ *public method
Elasticsearch.Net.MultiGetRequestParameters.Fields* _Removed (Breaking)_
*public class Elasticsearch.Net.OptimizeRequestParameters* _Removed
(Breaking)_ *public method
Elasticsearch.Net.PutScriptRequestParameters.OpType* _Removed
(Breaking)_ *public method
Elasticsearch.Net.PutScriptRequestParameters.Version* _Removed
(Breaking)_ *public method
Elasticsearch.Net.PutScriptRequestParameters.VersionType* _Removed
(Breaking)_ *public method
Elasticsearch.Net.PutSearchTemplateRequestParameters.OpType* _Removed
(Breaking)_ *public method
Elasticsearch.Net.PutSearchTemplateRequestParameters.Version* _Removed
(Breaking)_ *public method
Elasticsearch.Net.PutSearchTemplateRequestParameters.VersionType*
_Removed (Breaking)_ *public class
Elasticsearch.Net.PutWarmerRequestParameters* _Removed (Breaking)_
*public method
Elasticsearch.Net.ReindexOnServerRequestParameters.Consistency* _Removed
(Breaking)_ *public method
Elasticsearch.Net.RequestConfigurationDescriptor.AcceptContentType*
_Removed (Breaking)_ *public method
Elasticsearch.Net.RequestConfigurationDescriptor.CancellationToken*
_Removed (Breaking)_ *public property
Elasticsearch.Net.RequestData.CancellationToken* _Removed (Breaking)_
*public class Elasticsearch.Net.SearchExistsRequestParameters* _Removed
(Breaking)_ *public class
Elasticsearch.Net.TasksCancelRequestParameters* _Removed (Breaking)_
*public class Elasticsearch.Net.TasksListRequestParameters* _Removed
(Breaking)_ *public method
Elasticsearch.Net.TermVectorsRequestParameters.Dfs* _Removed (Breaking)_
*public method
Elasticsearch.Net.UpdateByQueryRequestParameters.Consistency* _Removed
(Breaking)_ *public method
Elasticsearch.Net.UpdateByQueryRequestParameters.Fields* _Removed
(Breaking)_ *public method
Elasticsearch.Net.UpdateRequestParameters.Consistency* _Removed
(Breaking)_ *public method
Elasticsearch.Net.UpdateRequestParameters.Script* _Removed (Breaking)_
*public method Elasticsearch.Net.UpdateRequestParameters.ScriptedUpsert*
_Removed (Breaking)_ *public method
Elasticsearch.Net.UpdateRequestParameters.ScriptId* _Removed (Breaking)_
*public method
Elasticsearch.Net.UpgradeRequestParameters.AllowNoIndices* _Removed
(Breaking)_ *public class
Elasticsearch.Net.WatcherInfoRequestParameters* _Removed (Breaking)_
