:ref_current: https://www.elastic.co/guide/en/elasticsearch/reference/master

:github: https://github.com/elastic/elasticsearch-net

:nuget: https://www.nuget.org/packages

////
IMPORTANT NOTE
==============
This file has been generated from https://github.com/elastic/elasticsearch-net/tree/master/src/Tests/ClientConcepts/Certificates/WorkingWithCertificates.doc.cs. 
If you wish to submit a PR for any spelling mistakes, typos or grammatical errors for this file,
please modify the original csharp file found at the link and submit the PR with that change. Thanks!
////

[[working-with-certificates]]
== Working with certificates

=== Server Certificates

If you've enabled SSL on elasticsearch with x-pack or through a proxy in front of elasticsearch and the Certificate Authority (CA)
That generated the certificate is trusted by the machine running the client code there should be nothing you'll have to do to to talk
to over https with the client. If you are using your own CA which is not trusted .NET won't allow you to make https calls to that endpoint.

.NET allows you to preempt this though through a custom validation through the the global static `ServicePointManager.ServerCertificateValidationCallback`.
Most examples you will find on the .NET will simply return `true` from this delegate and call it quits. This is not advisable as this will allow any HTTPS
traffic in the current AppDomain and not run any validations. Imagine you deploy a web app that talks to Elasticsearch over HTTPS but also some third party
SOAP/WSDL endpoint setting `ServicePointManager.ServerCertificateValidationCallback += (sender, cert, chain, errors) => true;` will skip validation of BOTH
Elasticsearch and that external web service.

.NET also allows you to set that callback per service endpoint and Elasticsearch.NET/NEST exposes this through connection settings.
You can do your own validation in that handler or simply assign baked in handler that we ship with out of the box on the static
class `CertificateValidations`.

The two most basic ones are `AllowAll` and `DenyAll` which does accept or deny any ssl trafic to our nodes`:

If your client application however has access to the public CA certificate locally Elasticsearch.NET/NEST ships with handy helpers that assert
that the certificate that the server presented was one that came from our local CA certificate. If you use x-pack's `certgen` tool to
[generate SSL certificates] https://www.elastic.co/guide/en/x-pack/current/ssl-tls.html)[] the generated node certificate does not include the CA in the
certificate chain. This to cut back on SSL handshake size. In those case you can use `CertificateValidations.AuthorityIsRoot` and pass it your local copy
of the CA public key to assert that the certificate the server presented was generated off that.

If your local copy does not match the servers CA Elasticsearch.NET/NEST will fail to connect

If you go for a vendor generated SSL certificate its common practice for them to include the CA and any intermediary CA's in the certificate chain
in those case use `CertificateValidations.AuthorityPartOfChain` which validates that the local CA certificate is part of that chain and was used to
generate the servers key.

=== Client Certificates

X-Pack also allows you to configure a [PKI realm] https://www.elastic.co/guide/en/x-pack/current/pki-realm.html)[] to enable user authentication
through client certificates. The `certgen` tool included with X-Pack allows you to
[generate client certificates as well] https://www.elastic.co/guide/en/x-pack/current/ssl-tls.html#CO13-4)[] and assign the distinguished name (DN) of the
certificate as a user with a certain role.

certgen by default only generates a public certificate `.cer`) and a private key `.key`. To authenticate with client certificates you need to present both
as one certificate. The easiest way to do this is to generate a `pfx` or `p12` file from the two and present that to `new X509Certificate(pathToPfx)`.

If you do not have a way to run `openssl` or `Pvk2Pfx` to do so as part of your deployments the clients ships with a handy helper to generate one
on the fly in code based of `.cer`  and `.key` files that `certgen` outputs. Sadly this is not available on .NET core because we can no longer set `PublicKey`
crypto service provider.

You can set Client Certificates to use on all connections on `ConnectionSettings`

Or per request on `RequestConfiguration` which will take precedence over the ones defined on `ConnectionConfiguration`

=== Object Initializer Syntax Example

[source,csharp]
----
new RootNodeInfoRequest
{
    RequestConfiguration = new RequestConfiguration
    {
        ClientCertificates = new X509Certificate2Collection { new X509Certificate2(this.BadCertificate) }
    }
}
----

=== Fluent DSL Example

[source,csharp]
----
s => s
.RequestConfiguration(r => r
    .ClientCertificate(this.BadCertificate)

)
----

