// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.
//
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// ------------------------------------------------
//
// This file is automatically generated.
// Please do not edit these files manually.
//
// ------------------------------------------------

using Elastic.Transport.Products.Elasticsearch;
using System.Collections.Generic;
using System.Text.Json.Serialization;

#nullable restore
namespace Elastic.Clients.Elasticsearch.Ml
{
	public partial class MlPutDatafeedResponse : ElasticsearchResponseBase
	{
		[JsonInclude]
		[JsonPropertyName("aggregations")]
		public Dictionary<string, Elastic.Clients.Elasticsearch.Aggregations.AggregationContainer> Aggregations { get; init; }

		[JsonInclude]
		[JsonPropertyName("chunking_config")]
		public Elastic.Clients.Elasticsearch.Ml.ChunkingConfig ChunkingConfig { get; init; }

		[JsonInclude]
		[JsonPropertyName("datafeed_id")]
		public string DatafeedId { get; init; }

		[JsonInclude]
		[JsonPropertyName("delayed_data_check_config")]
		public Elastic.Clients.Elasticsearch.Ml.DelayedDataCheckConfig? DelayedDataCheckConfig { get; init; }

		[JsonInclude]
		[JsonPropertyName("frequency")]
		public Elastic.Clients.Elasticsearch.Time Frequency { get; init; }

		[JsonInclude]
		[JsonPropertyName("indices")]
		public IReadOnlyCollection<string> Indices { get; init; }

		[JsonInclude]
		[JsonPropertyName("indices_options")]
		public Elastic.Clients.Elasticsearch.IndicesOptions? IndicesOptions { get; init; }

		[JsonInclude]
		[JsonPropertyName("job_id")]
		public string JobId { get; init; }

		[JsonInclude]
		[JsonPropertyName("max_empty_searches")]
		public int MaxEmptySearches { get; init; }

		[JsonInclude]
		[JsonPropertyName("query")]
		public Elastic.Clients.Elasticsearch.QueryDsl.QueryContainer Query { get; init; }

		[JsonInclude]
		[JsonPropertyName("query_delay")]
		public Elastic.Clients.Elasticsearch.Time QueryDelay { get; init; }

		[JsonInclude]
		[JsonPropertyName("runtime_mappings")]
		public Dictionary<Elastic.Clients.Elasticsearch.Field, IReadOnlyCollection<Elastic.Clients.Elasticsearch.Mapping.RuntimeField>>? RuntimeMappings { get; init; }

		[JsonInclude]
		[JsonPropertyName("script_fields")]
		public Dictionary<string, Elastic.Clients.Elasticsearch.ScriptField>? ScriptFields { get; init; }

		[JsonInclude]
		[JsonPropertyName("scroll_size")]
		public int ScrollSize { get; init; }
	}
}