:ref_current: https://www.elastic.co/guide/en/elasticsearch/reference/master

:github: https://github.com/elastic/elasticsearch-net

:nuget: https://www.nuget.org/packages

////
IMPORTANT NOTE
==============
This file has been generated from https://github.com/elastic/elasticsearch-net/tree/master/src/Tests/Aggregations/Bucket/Filter/FilterAggregationUsageTests.cs.
If you wish to submit a PR for any spelling mistakes, typos or grammatical errors for this file,
please modify the original csharp file found at the link and submit the PR with that change. Thanks!
////

[[filter-aggregation-usage]]
=== Filter Aggregation Usage

Defines a single bucket of all the documents in the current document set context that match a specified filter.
Often this will be used to narrow down the current aggregation context to a specific set of documents.

Be sure to read the Elasticsearch documentation on {ref_current}/search-aggregations-bucket-filter-aggregation.html[Filter Aggregation]

=== Handling Responses

Using the `.Aggs` aggregation helper we can fetch our aggregation results easily
in the correct type.
//<<aggs-vs-aggregations, Be sure to read more about .Aggs vs .Aggregations>>

==== Handling Responses

[source,csharp]
----
response.ShouldBeValid();

var filterAgg = response.Aggregations.Filter("bethels_projects");
filterAgg.Should().NotBeNull();
filterAgg.DocCount.Should().BeGreaterThan(0);
var tags = filterAgg.Terms("project_tags");
tags.Should().NotBeNull();
tags.Buckets.Should().NotBeEmpty();
----

[float]
== Empty Filter

When the collection of filters is empty or all are conditionless, NEST will serialize them
to an empty object.

[source,csharp]
----
response.ShouldNotBeValid();
----

[source,csharp]
----
response.ShouldBeValid();
response.Aggregations.Filter(_aggName).DocCount.Should().BeGreaterThan(0);
----
