// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.
//
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// ------------------------------------------------
//
// This file is automatically generated.
// Please do not edit these files manually.
//
// ------------------------------------------------

#nullable restore

using System;
using System.Linq;
using Elastic.Clients.Elasticsearch.Serialization;

namespace Elastic.Clients.Elasticsearch.Ingest;

/// <include file="../../SpecReferences.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor']/*"/>
[System.Text.Json.Serialization.JsonConverter(typeof(Elastic.Clients.Elasticsearch.Ingest.Json.DateIndexNameProcessorConverter))]
public sealed partial class DateIndexNameProcessor
{
	[System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
	public DateIndexNameProcessor(System.Collections.Generic.ICollection<string> dateFormats, string dateRounding, Elastic.Clients.Elasticsearch.Field field)
	{
		DateFormats = dateFormats;
		DateRounding = dateRounding;
		Field = field;
	}

	public DateIndexNameProcessor()
	{
	}

	[System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
	internal DateIndexNameProcessor(Elastic.Clients.Elasticsearch.Serialization.JsonConstructorSentinel sentinel)
	{
		_ = sentinel;
	}

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#date_formats']/*"/>
	public required System.Collections.Generic.ICollection<string> DateFormats { get; set; }

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#date_rounding']/*"/>
	public required string DateRounding { get; set; }

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#description']/*"/>
	public string? Description { get; set; }

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#field']/*"/>
	public required Elastic.Clients.Elasticsearch.Field Field { get; set; }

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#if']/*"/>
	public string? If { get; set; }

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#ignore_failure']/*"/>
	public bool? IgnoreFailure { get; set; }

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#index_name_format']/*"/>
	public string? IndexNameFormat { get; set; }

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#index_name_prefix']/*"/>
	public string? IndexNamePrefix { get; set; }

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#locale']/*"/>
	public string? Locale { get; set; }

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#on_failure']/*"/>
	public System.Collections.Generic.ICollection<Elastic.Clients.Elasticsearch.Ingest.Processor>? OnFailure { get; set; }

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#tag']/*"/>
	public string? Tag { get; set; }

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#timezone']/*"/>
	public string? Timezone { get; set; }
}

/// <include file="../../SpecReferences.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor']/*"/>
public readonly partial struct DateIndexNameProcessorDescriptor<TDocument>
{
	internal Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessor Instance { get; init; }

	[System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
	public DateIndexNameProcessorDescriptor(Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessor instance)
	{
		Instance = instance;
	}

	[System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
	public DateIndexNameProcessorDescriptor()
	{
		Instance = new Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessor(Elastic.Clients.Elasticsearch.Serialization.JsonConstructorSentinel.Instance);
	}

	public static explicit operator Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor<TDocument>(Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessor instance) => new Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor<TDocument>(instance);
	public static implicit operator Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessor(Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor<TDocument> descriptor) => descriptor.Instance;

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#date_formats']/*"/>
	public Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor<TDocument> DateFormats(System.Collections.Generic.ICollection<string> value)
	{
		Instance.DateFormats = value;
		return this;
	}

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#date_formats']/*"/>
	public Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor<TDocument> DateFormats(params string[] values)
	{
		Instance.DateFormats = [.. values];
		return this;
	}

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#date_rounding']/*"/>
	public Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor<TDocument> DateRounding(string value)
	{
		Instance.DateRounding = value;
		return this;
	}

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#description']/*"/>
	public Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor<TDocument> Description(string? value)
	{
		Instance.Description = value;
		return this;
	}

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#field']/*"/>
	public Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor<TDocument> Field(Elastic.Clients.Elasticsearch.Field value)
	{
		Instance.Field = value;
		return this;
	}

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#field']/*"/>
	public Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor<TDocument> Field(System.Linq.Expressions.Expression<System.Func<TDocument, object?>> value)
	{
		Instance.Field = value;
		return this;
	}

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#if']/*"/>
	public Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor<TDocument> If(string? value)
	{
		Instance.If = value;
		return this;
	}

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#ignore_failure']/*"/>
	public Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor<TDocument> IgnoreFailure(bool? value = true)
	{
		Instance.IgnoreFailure = value;
		return this;
	}

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#index_name_format']/*"/>
	public Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor<TDocument> IndexNameFormat(string? value)
	{
		Instance.IndexNameFormat = value;
		return this;
	}

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#index_name_prefix']/*"/>
	public Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor<TDocument> IndexNamePrefix(string? value)
	{
		Instance.IndexNamePrefix = value;
		return this;
	}

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#locale']/*"/>
	public Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor<TDocument> Locale(string? value)
	{
		Instance.Locale = value;
		return this;
	}

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#on_failure']/*"/>
	public Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor<TDocument> OnFailure(System.Collections.Generic.ICollection<Elastic.Clients.Elasticsearch.Ingest.Processor>? value)
	{
		Instance.OnFailure = value;
		return this;
	}

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#on_failure']/*"/>
	public Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor<TDocument> OnFailure(params Elastic.Clients.Elasticsearch.Ingest.Processor[] values)
	{
		Instance.OnFailure = [.. values];
		return this;
	}

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#on_failure']/*"/>
	public Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor<TDocument> OnFailure(params System.Action<Elastic.Clients.Elasticsearch.Ingest.ProcessorDescriptor<TDocument>>[] actions)
	{
		var items = new System.Collections.Generic.List<Elastic.Clients.Elasticsearch.Ingest.Processor>();
		foreach (var action in actions)
		{
			items.Add(Elastic.Clients.Elasticsearch.Ingest.ProcessorDescriptor<TDocument>.Build(action));
		}

		Instance.OnFailure = items;
		return this;
	}

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#tag']/*"/>
	public Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor<TDocument> Tag(string? value)
	{
		Instance.Tag = value;
		return this;
	}

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#timezone']/*"/>
	public Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor<TDocument> Timezone(string? value)
	{
		Instance.Timezone = value;
		return this;
	}

	[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	internal static Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessor Build(System.Action<Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor<TDocument>> action)
	{
		var builder = new Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor<TDocument>(new Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessor(Elastic.Clients.Elasticsearch.Serialization.JsonConstructorSentinel.Instance));
		action.Invoke(builder);
		return builder.Instance;
	}
}

/// <include file="../../SpecReferences.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor']/*"/>
public readonly partial struct DateIndexNameProcessorDescriptor
{
	internal Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessor Instance { get; init; }

	[System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
	public DateIndexNameProcessorDescriptor(Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessor instance)
	{
		Instance = instance;
	}

	[System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
	public DateIndexNameProcessorDescriptor()
	{
		Instance = new Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessor(Elastic.Clients.Elasticsearch.Serialization.JsonConstructorSentinel.Instance);
	}

	public static explicit operator Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor(Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessor instance) => new Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor(instance);
	public static implicit operator Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessor(Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor descriptor) => descriptor.Instance;

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#date_formats']/*"/>
	public Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor DateFormats(System.Collections.Generic.ICollection<string> value)
	{
		Instance.DateFormats = value;
		return this;
	}

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#date_formats']/*"/>
	public Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor DateFormats(params string[] values)
	{
		Instance.DateFormats = [.. values];
		return this;
	}

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#date_rounding']/*"/>
	public Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor DateRounding(string value)
	{
		Instance.DateRounding = value;
		return this;
	}

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#description']/*"/>
	public Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor Description(string? value)
	{
		Instance.Description = value;
		return this;
	}

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#field']/*"/>
	public Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor Field(Elastic.Clients.Elasticsearch.Field value)
	{
		Instance.Field = value;
		return this;
	}

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#field']/*"/>
	public Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor Field<T>(System.Linq.Expressions.Expression<System.Func<T, object?>> value)
	{
		Instance.Field = value;
		return this;
	}

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#if']/*"/>
	public Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor If(string? value)
	{
		Instance.If = value;
		return this;
	}

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#ignore_failure']/*"/>
	public Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor IgnoreFailure(bool? value = true)
	{
		Instance.IgnoreFailure = value;
		return this;
	}

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#index_name_format']/*"/>
	public Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor IndexNameFormat(string? value)
	{
		Instance.IndexNameFormat = value;
		return this;
	}

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#index_name_prefix']/*"/>
	public Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor IndexNamePrefix(string? value)
	{
		Instance.IndexNamePrefix = value;
		return this;
	}

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#locale']/*"/>
	public Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor Locale(string? value)
	{
		Instance.Locale = value;
		return this;
	}

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#on_failure']/*"/>
	public Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor OnFailure(System.Collections.Generic.ICollection<Elastic.Clients.Elasticsearch.Ingest.Processor>? value)
	{
		Instance.OnFailure = value;
		return this;
	}

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#on_failure']/*"/>
	public Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor OnFailure(params Elastic.Clients.Elasticsearch.Ingest.Processor[] values)
	{
		Instance.OnFailure = [.. values];
		return this;
	}

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#on_failure']/*"/>
	public Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor OnFailure(params System.Action<Elastic.Clients.Elasticsearch.Ingest.ProcessorDescriptor>[] actions)
	{
		var items = new System.Collections.Generic.List<Elastic.Clients.Elasticsearch.Ingest.Processor>();
		foreach (var action in actions)
		{
			items.Add(Elastic.Clients.Elasticsearch.Ingest.ProcessorDescriptor.Build(action));
		}

		Instance.OnFailure = items;
		return this;
	}

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#on_failure']/*"/>
	public Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor OnFailure<T>(params System.Action<Elastic.Clients.Elasticsearch.Ingest.ProcessorDescriptor<T>>[] actions)
	{
		var items = new System.Collections.Generic.List<Elastic.Clients.Elasticsearch.Ingest.Processor>();
		foreach (var action in actions)
		{
			items.Add(Elastic.Clients.Elasticsearch.Ingest.ProcessorDescriptor<T>.Build(action));
		}

		Instance.OnFailure = items;
		return this;
	}

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#tag']/*"/>
	public Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor Tag(string? value)
	{
		Instance.Tag = value;
		return this;
	}

	/// <include file="DateIndexNameProcessor.g.xml" path="doc/member[@key='ingest._types.DateIndexNameProcessor#timezone']/*"/>
	public Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor Timezone(string? value)
	{
		Instance.Timezone = value;
		return this;
	}

	[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	internal static Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessor Build(System.Action<Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor> action)
	{
		var builder = new Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessorDescriptor(new Elastic.Clients.Elasticsearch.Ingest.DateIndexNameProcessor(Elastic.Clients.Elasticsearch.Serialization.JsonConstructorSentinel.Instance));
		action.Invoke(builder);
		return builder.Instance;
	}
}