[[installation]]
== Installation

This page shows you how to install the .NET client for {es}.

IMPORTANT: The v8 client for .NET is currently in pre-release and not supported for 
production use. We provide it for testing and migration planning purposes. 
You may continue to use the 7.17.x release of the client to communicate with v8 
Elasticsearch servers using compatibility mode. Refer to the 
https://www.elastic.co/guide/en/elasticsearch/client/net-api/7.17/connecting-to-elasticsearch-v8.html[Connecting to Elasticsearch v8.x using the v7.17.x client documentation] 
for guidance on configuring the 7.17.x client.

[discrete]
[[dot-net-client]]
=== Installing the .NET client

For SDK style projects, you can install the {es} client by running the following 
.NET CLI command in your terminal:

[source,text]
----
dotnet add package Elastic.Clients.Elasticsearch -prerelease
----

This command adds a package reference to your project (csproj) file for the 
latest stable version of the client.

If you prefer, you may also manually add a package reference inside your project 
file:

[source,shell]
----
<PackageReference Include="Elastic.Clients.Elasticsearch" Version="8.0.0-alpha.5" />
----

To install a different version, modify the version as necessary. During the prerelease 
phase, we highly recommend using the latest pre-release version.

For Visual Studio users, the .NET client can also be installed from the Package
Manager Console inside Visual Studio using the following command:

[source,shell]
----
Install-Package Elastic.Clients.Elasticsearch -IncludePrerelease
----

Alternatively, search for `Elastic.Clients.Elasticsearch` in the NuGet Package 
Manager UI.

NOTE: By default, NuGet does not include pre-release versions when working with packages, 
but you can change this behavior by checking the "Include prerelease" option in the 
Package Manager UI.

To learn how to connect the {es} client, refer to the <<connecting,Connecting>> section.

[discrete]
[[compatibility]]
=== Compatibility

The {es} client is compatible with currently maintained .NET runtime versions. 
Compatibility with End of Life (EOL) .NET runtimes is not guaranteed or supported.

Language clients are forward compatible; meaning that clients support 
communicating with greater or equal minor versions of {es}. {es} language 
clients are only backward compatible with default distributions and without 
guarantees made.

Refer to the https://www.elastic.co/support/eol[end-of-life policy] for more 
information.
