:ref_current: https://www.elastic.co/guide/en/elasticsearch/reference/2.3

:github: https://github.com/elastic/elasticsearch-net

:nuget: https://www.nuget.org/packages

[[profile-usage]]
== Profile Usage

WARNING: This functionality is experimental and may be changed or removed completely in a future release.

The Profile API provides detailed timing information about the execution of individual components in a query.
It gives the user insight into how queries are executed at a low level so that the user can understand
why certain queries are slow, and take steps to improve their slow queries.

The output from the Profile API is very verbose, especially for complicated queries executed across many shards.
Pretty-printing the response is recommended to help understand the output

See the Elasticsearch documentation on {ref_current}/search-profile.html[Profile API] for more detail.

=== Fluent DSL Example

[source,csharp]
----
s => s
.Profile()
.Query(q => q
    .Term(p => p.Name, "elasticsearch")
)
----

=== Object Initializer Syntax Example

[source,csharp]
----
new SearchRequest<Project>
{
    Profile = true,
    Query = new TermQuery
    {
        Field = "name",
        Value = "elasticsearch"
    }
}
----

[source,javascript]
.Example json output
----
{
  "profile": true,
  "query": {
    "term": {
      "name": {
        "value": "elasticsearch"
      }
    }
  }
}
----

