:ref_current: https://www.elastic.co/guide/en/elasticsearch/reference/5.3

:xpack_current: https://www.elastic.co/guide/en/x-pack/5.3

:github: https://github.com/elastic/elasticsearch-net

:nuget: https://www.nuget.org/packages

////
IMPORTANT NOTE
==============
This file has been generated from https://github.com/elastic/elasticsearch-net/tree/5.x/src/Tests/ClientConcepts/HighLevel/Inference/FeaturesInference.doc.cs. 
If you wish to submit a PR for any spelling mistakes, typos or grammatical errors for this file,
please modify the original csharp file found at the link and submit the PR with that change. Thanks!
////

[[features-inference]]
=== Features inference

Some URIs in Elasticsearch take a `Feature` enum.
Within NEST, route values on the URI are represented as classes that implement an interface, `IUrlParameter`.
Since enums _cannot_ implement interfaces in C#, a route parameter that would be of type `Feature` is represented using the `Features` class that
the `Feature` enum implicitly converts to.

==== Constructor

Using the `Features` constructor directly is possible but rather involved 

[source,csharp]
----
Features fieldString = Feature.Mappings | Feature.Aliases;
Expect("_mappings,_aliases")
    .WhenSerializing(fieldString);
----

Here we new an GET index elasticsearch request which takes Indices and Features.
Notice how we can use the Feature enum directly.

[source,csharp]
----
var request = new GetIndexRequest(All, Feature.Settings);
----

