:ref_current: https://www.elastic.co/guide/en/elasticsearch/reference/7.10

:github: https://github.com/elastic/elasticsearch-net

:nuget: https://www.nuget.org/packages

////
IMPORTANT NOTE
==============
This file has been generated from https://github.com/elastic/elasticsearch-net/tree/7.x/src/Tests/Tests/ClientConcepts/HighLevel/Inference/TypesAndRelationsInference.doc.cs. 
If you wish to submit a PR for any spelling mistakes, typos or grammatical errors for this file,
please modify the original csharp file found at the link and submit the PR with that change. Thanks!
////

[[types-and-relations-inference]]
=== Relation names inference

[[relation-names]]
[float]
=== Relation names

Prior to Elasticsearch 6.x you could have multiple types per index. They acted as a discrimatory column but were often
confused with tables. The fact that the mapping API's treated them as seperate entities did not help.

The general guideline has always been to use a single type per index. Starting from 6.x this is also enforced.
Some features still need to store multiple types in a single index such as Parent/Child join relations.

Both `Parent` and `Child` will need to have resolve to the same typename to be indexed into the same index.

Therefore in 6.x we need a different type that translates a CLR type to a join relation. This can be configured seperately
using `.RelationName()`

[source,csharp]
----
var settings = new ConnectionSettings()
    .DefaultMappingFor<CommitActivity>(m => m
        .IndexName("projects-and-commits")
        .RelationName("commits")
    )
    .DefaultMappingFor<Project>(m => m
        .IndexName("projects-and-commits")
        .RelationName("projects")
    );

var resolver = new RelationNameResolver(settings);
var relation = resolver.Resolve<Project>();
relation.Should().Be("projects");

relation = resolver.Resolve<CommitActivity>();
relation.Should().Be("commits");
----

`RelationName` uses the `DefaultTypeNameInferrer` to translate CLR types to a string representation.

Explicit `TypeName` configuration does not affect how the default relation for the CLR type
is represented though

[source,csharp]
----
var settings = new ConnectionSettings()
    .DefaultMappingFor<Project>(m => m
        .IndexName("projects-and-commits")
    );

var resolver = new RelationNameResolver(settings);
var relation = resolver.Resolve<Project>();
relation.Should().Be("project");
----

