// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.
//
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// ------------------------------------------------
//
// This file is automatically generated.
// Please do not edit these files manually.
//
// ------------------------------------------------

#nullable restore

using Elastic.Clients.Elasticsearch.Serialization;
using System;
using System.Linq;

namespace Elastic.Clients.Elasticsearch.MachineLearning;

public partial class DataCounts : RequestConverter.ICodeFormattable
{
	public void FormatCode(System.Text.StringBuilder sb)
	{
		var instance = this;
		sb.Append("new()");
		var hasProps = false;
		{
			sb.Append(hasProps ? ", " : " { ");
			hasProps = true;
			sb.Append("BucketCount = ");
			sb.Append(instance.BucketCount);
			sb.Append("L");
		}

		if (instance.EarliestRecordTimestamp is not null)
		{
			sb.Append(hasProps ? ", " : " { ");
			hasProps = true;
			sb.Append("EarliestRecordTimestamp = ");
			sb.Append(instance.EarliestRecordTimestamp.Value);
			sb.Append("L");
		}

		{
			sb.Append(hasProps ? ", " : " { ");
			hasProps = true;
			sb.Append("EmptyBucketCount = ");
			sb.Append(instance.EmptyBucketCount);
			sb.Append("L");
		}

		{
			sb.Append(hasProps ? ", " : " { ");
			hasProps = true;
			sb.Append("InputBytes = ");
			sb.Append(instance.InputBytes);
			sb.Append("L");
		}

		{
			sb.Append(hasProps ? ", " : " { ");
			hasProps = true;
			sb.Append("InputFieldCount = ");
			sb.Append(instance.InputFieldCount);
			sb.Append("L");
		}

		{
			sb.Append(hasProps ? ", " : " { ");
			hasProps = true;
			sb.Append("InputRecordCount = ");
			sb.Append(instance.InputRecordCount);
			sb.Append("L");
		}

		{
			sb.Append(hasProps ? ", " : " { ");
			hasProps = true;
			sb.Append("InvalidDateCount = ");
			sb.Append(instance.InvalidDateCount);
			sb.Append("L");
		}

		{
			sb.Append(hasProps ? ", " : " { ");
			hasProps = true;
			sb.Append("JobId = ");
			sb.Append("\"");
			sb.Append(instance.JobId);
			sb.Append("\"");
		}

		if (instance.LastDataTime is not null)
		{
			sb.Append(hasProps ? ", " : " { ");
			hasProps = true;
			sb.Append("LastDataTime = ");
			sb.Append(instance.LastDataTime.Value);
			sb.Append("L");
		}

		if (instance.LatestBucketTimestamp is not null)
		{
			sb.Append(hasProps ? ", " : " { ");
			hasProps = true;
			sb.Append("LatestBucketTimestamp = ");
			sb.Append(instance.LatestBucketTimestamp.Value);
			sb.Append("L");
		}

		if (instance.LatestEmptyBucketTimestamp is not null)
		{
			sb.Append(hasProps ? ", " : " { ");
			hasProps = true;
			sb.Append("LatestEmptyBucketTimestamp = ");
			sb.Append(instance.LatestEmptyBucketTimestamp.Value);
			sb.Append("L");
		}

		if (instance.LatestRecordTimestamp is not null)
		{
			sb.Append(hasProps ? ", " : " { ");
			hasProps = true;
			sb.Append("LatestRecordTimestamp = ");
			sb.Append(instance.LatestRecordTimestamp.Value);
			sb.Append("L");
		}

		if (instance.LatestSparseBucketTimestamp is not null)
		{
			sb.Append(hasProps ? ", " : " { ");
			hasProps = true;
			sb.Append("LatestSparseBucketTimestamp = ");
			sb.Append(instance.LatestSparseBucketTimestamp.Value);
			sb.Append("L");
		}

		if (instance.LogTime is not null)
		{
			sb.Append(hasProps ? ", " : " { ");
			hasProps = true;
			sb.Append("LogTime = ");
			sb.Append(instance.LogTime.Value);
			sb.Append("L");
		}

		{
			sb.Append(hasProps ? ", " : " { ");
			hasProps = true;
			sb.Append("MissingFieldCount = ");
			sb.Append(instance.MissingFieldCount);
			sb.Append("L");
		}

		{
			sb.Append(hasProps ? ", " : " { ");
			hasProps = true;
			sb.Append("OutOfOrderTimestampCount = ");
			sb.Append(instance.OutOfOrderTimestampCount);
			sb.Append("L");
		}

		{
			sb.Append(hasProps ? ", " : " { ");
			hasProps = true;
			sb.Append("ProcessedFieldCount = ");
			sb.Append(instance.ProcessedFieldCount);
			sb.Append("L");
		}

		{
			sb.Append(hasProps ? ", " : " { ");
			hasProps = true;
			sb.Append("ProcessedRecordCount = ");
			sb.Append(instance.ProcessedRecordCount);
			sb.Append("L");
		}

		{
			sb.Append(hasProps ? ", " : " { ");
			hasProps = true;
			sb.Append("SparseBucketCount = ");
			sb.Append(instance.SparseBucketCount);
			sb.Append("L");
		}

		if (hasProps)
			sb.Append(" }");
	}
}