// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.
//
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// ------------------------------------------------
//
// This file is automatically generated.
// Please do not edit these files manually.
//
// ------------------------------------------------

#nullable restore

using Elastic.Clients.Elasticsearch.Serialization;
using System;
using System.Linq;

namespace Elastic.Clients.Elasticsearch.MachineLearning;

public partial class Preprocessor : RequestConverter.ICodeFormattable
{
	public void FormatCode(RequestConverter.CodeWriter writer)
	{
		var __init = writer.BeginObjectInitializer("Preprocessor");
		if (FrequencyEncoding is not null)
		{
			__init.Property("FrequencyEncoding");
			FrequencyEncoding.FormatCode(writer);
		}

		if (OneHotEncoding is not null)
		{
			__init.Property("OneHotEncoding");
			OneHotEncoding.FormatCode(writer);
		}

		if (TargetMeanEncoding is not null)
		{
			__init.Property("TargetMeanEncoding");
			TargetMeanEncoding.FormatCode(writer);
		}

		__init.Dispose();
	}
}