// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.
//
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// ------------------------------------------------
//
// This file is automatically generated.
// Please do not edit these files manually.
//
// ------------------------------------------------

#nullable restore

using System;
using System.Linq;
using Elastic.Clients.Elasticsearch.Serialization;

namespace Elastic.Clients.Elasticsearch.Core.RankEval;

/// <include file="RankEvalMetricDiscountedCumulativeGain.g.xml" path="doc/member[@key='_global.rank_eval.RankEvalMetricDiscountedCumulativeGain']/*"/>
/// <include file="../../../SpecReferences.xml" path="doc/member[@key='_global.rank_eval.RankEvalMetricDiscountedCumulativeGain']/*"/>
[System.Text.Json.Serialization.JsonConverter(typeof(Elastic.Clients.Elasticsearch.Core.RankEval.Json.RankEvalMetricDiscountedCumulativeGainConverter))]
public sealed partial class RankEvalMetricDiscountedCumulativeGain
{
	public RankEvalMetricDiscountedCumulativeGain()
	{
	}

	[System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
	internal RankEvalMetricDiscountedCumulativeGain(Elastic.Clients.Elasticsearch.Serialization.JsonConstructorSentinel sentinel)
	{
		_ = sentinel;
	}

	/// <include file="RankEvalMetricDiscountedCumulativeGain.g.xml" path="doc/member[@key='_global.rank_eval.RankEvalMetricDiscountedCumulativeGain#k']/*"/>
	public int? K { get; set; }

	/// <include file="RankEvalMetricDiscountedCumulativeGain.g.xml" path="doc/member[@key='_global.rank_eval.RankEvalMetricDiscountedCumulativeGain#normalize']/*"/>
	public bool? Normalize { get; set; }
}

/// <include file="RankEvalMetricDiscountedCumulativeGain.g.xml" path="doc/member[@key='_global.rank_eval.RankEvalMetricDiscountedCumulativeGain']/*"/>
/// <include file="../../../SpecReferences.xml" path="doc/member[@key='_global.rank_eval.RankEvalMetricDiscountedCumulativeGain']/*"/>
public readonly partial struct RankEvalMetricDiscountedCumulativeGainDescriptor
{
	internal Elastic.Clients.Elasticsearch.Core.RankEval.RankEvalMetricDiscountedCumulativeGain Instance { get; init; }

	[System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
	public RankEvalMetricDiscountedCumulativeGainDescriptor(Elastic.Clients.Elasticsearch.Core.RankEval.RankEvalMetricDiscountedCumulativeGain instance)
	{
		Instance = instance;
	}

	[System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
	public RankEvalMetricDiscountedCumulativeGainDescriptor()
	{
		Instance = new Elastic.Clients.Elasticsearch.Core.RankEval.RankEvalMetricDiscountedCumulativeGain(Elastic.Clients.Elasticsearch.Serialization.JsonConstructorSentinel.Instance);
	}

	public static explicit operator Elastic.Clients.Elasticsearch.Core.RankEval.RankEvalMetricDiscountedCumulativeGainDescriptor(Elastic.Clients.Elasticsearch.Core.RankEval.RankEvalMetricDiscountedCumulativeGain instance) => new Elastic.Clients.Elasticsearch.Core.RankEval.RankEvalMetricDiscountedCumulativeGainDescriptor(instance);
	public static implicit operator Elastic.Clients.Elasticsearch.Core.RankEval.RankEvalMetricDiscountedCumulativeGain(Elastic.Clients.Elasticsearch.Core.RankEval.RankEvalMetricDiscountedCumulativeGainDescriptor descriptor) => descriptor.Instance;

	/// <include file="RankEvalMetricDiscountedCumulativeGain.g.xml" path="doc/member[@key='_global.rank_eval.RankEvalMetricDiscountedCumulativeGain#k']/*"/>
	public Elastic.Clients.Elasticsearch.Core.RankEval.RankEvalMetricDiscountedCumulativeGainDescriptor K(int? value)
	{
		Instance.K = value;
		return this;
	}

	/// <include file="RankEvalMetricDiscountedCumulativeGain.g.xml" path="doc/member[@key='_global.rank_eval.RankEvalMetricDiscountedCumulativeGain#normalize']/*"/>
	public Elastic.Clients.Elasticsearch.Core.RankEval.RankEvalMetricDiscountedCumulativeGainDescriptor Normalize(bool? value = true)
	{
		Instance.Normalize = value;
		return this;
	}

	[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	internal static Elastic.Clients.Elasticsearch.Core.RankEval.RankEvalMetricDiscountedCumulativeGain Build(System.Action<Elastic.Clients.Elasticsearch.Core.RankEval.RankEvalMetricDiscountedCumulativeGainDescriptor>? action)
	{
		if (action is null)
		{
			return new Elastic.Clients.Elasticsearch.Core.RankEval.RankEvalMetricDiscountedCumulativeGain(Elastic.Clients.Elasticsearch.Serialization.JsonConstructorSentinel.Instance);
		}

		var builder = new Elastic.Clients.Elasticsearch.Core.RankEval.RankEvalMetricDiscountedCumulativeGainDescriptor(new Elastic.Clients.Elasticsearch.Core.RankEval.RankEvalMetricDiscountedCumulativeGain(Elastic.Clients.Elasticsearch.Serialization.JsonConstructorSentinel.Instance));
		action.Invoke(builder);
		return builder.Instance;
	}
}