name: Backport

on:
  pull_request_target:
    types: ["labeled", "closed"]

jobs:
  backport:
    name: Backport PR
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && !(contains(github.event.pull_request.labels.*.name, 'backport-'))
    
    steps:
      - name: Backport
        uses: sorenlouv/backport-github-action@929f69d04adbc196d982e60f02837b6cc00b3129
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          auto_backport_label_prefix: 'backport-'

      - name: Info log
        if: ${{ success() }}
        run: cat ~/.backport/backport.info.log
        
      - name: Debug log
        if: ${{ failure() }}
        run: cat ~/.backport/backport.debug.log
