name: Integration


on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.editorconfig'
  push:
    paths-ignore:
      - 'README.md'
      - '.editorconfig'
    branches:
      - main
      - master
      - '[0-9]+.[0-9]+'
      - '[0-9]+.x'

jobs:
  integration-tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        stack_version: [
           '7.0.0',
           '7.1.1',
           '7.2.1',
           '7.3.2',
           '7.4.2',
           '7.5.2',
           '7.6.2',
           '7.7.1',
           '7.8.1',
           '7.9.3',
           '7.10.2',
           '7.11.2',
           '7.12.1',
           '7.13.2',
           '7.14.2',
           '7.15.2',
           '7.16.3',
           '7.17.7',
           'latest-7'
        ]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v3 # reads version from 'global.json'
      - uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - uses: actions/cache@v2
        with:
          path: ~/.local/share/ElasticManaged/elasticsearch-${{ matrix.stack_version }}
          key: ${{ runner.os }}-elastic-managed-${{ matrix.stack_version }}
          restore-keys: |
            ${{ runner.os }}-elastic-managed-
            
      - run: "./build.sh integrate ${{ matrix.stack_version }} readonly,writable random:test_only_one --report"
        name: ${{ matrix.stack_version }}
      - name: Results ${{ matrix.stack_version }}
        # only report on if the previous run failed, otherwise this ends up being too noisy
        if: ${{ failure() }}
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: 'build/output/junit-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_failure: true
          require_tests: true
          check_name: ${{ matrix.stack_version }}
          
