name: License headers

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Check license headers
      run: |
        ./.github/check-license-headers.sh