name: 'CD'

on:
  release:
    types:
      - 'published'

jobs:
  release:
    name: 'Release'
    uses: ./.github/workflows/release.yml
    with:
      solution: 'Packages.slnf'
      release_tag: ${{ github.event.release.tag_name }}
      release_body: ${{ github.event.release.body }}
    secrets: 'inherit'

  docfx:
    name: 'DocFx'
    uses: ./.github/workflows/docfx.yml
    with:
      name: ${{ github.event.release.tag_name }}
      target_branch: 'refdoc'
    secrets: 'inherit'
