name: 'CD'

on:
  release:
    types:
      - 'published'

jobs:
  release:
    name: 'Release'
    if: ${{ startsWith(github.event.release.tag_name, 'serverless-') }}
    uses: ./.github/workflows/release.yml
    with:
      flavor: 'serverless'
      solution: 'Packages.Serverless.slnf'
      release_tag: ${{ github.event.release.tag_name }}
      release_body: ${{ github.event.release.body }}
    secrets: 'inherit'
