name: Unified Release

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.editorconfig'
  push:
    paths-ignore:
      - 'README.md'
      - '.editorconfig'
    branches:
      - main
      - '[0-9]+.[0-9]+'
      - '[0-9]+.x'

jobs:
  assemble:
    name: Assemble
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        stack_version: [ '9.0.0-SNAPSHOT']
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.300'
            
      - run: "./.ci/make.sh assemble ${{ matrix.stack_version }}"
        name: Assemble ${{ matrix.stack_version }}